DROP TABLE IF EXISTS serviceordercenterhis.tb_workbussinessjsoninfo;
CREATE TABLE serviceordercenterhis.`tb_workbussinessjsoninfo` (
  `Id` int(11) NOT NULL AUTO_INCREMENT COMMENT '自增主键',
  `WorkOrderId` char(12) DEFAULT NULL COMMENT '工单主单主键(tb_workorderinfo.Id)',
  `BussinessJson` json DEFAULT NULL COMMENT '处理人信息JSON',
  `InsertTime` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `Deleted` tinyint(1) NOT NULL DEFAULT '0',
  `appointTime` date GENERATED ALWAYS AS (json_unquote(json_extract(`BussinessJson`,_utf8mb4'$.appointTime'))) VIRTUAL COMMENT '(AFC)预计上门时间',
  `AppraisalStatus` int(11) GENERATED ALWAYS AS (json_unquote(json_extract(`BussinessJson`,_utf8mb4'$.AppraisalStatus'))) VIRTUAL COMMENT '(VHS)考核状态(0质量考核中 1质量考核通过 2质量考核驳回)',
  `v_FollowFrequency` varchar(12) CHARACTER SET utf8 COLLATE utf8_general_ci GENERATED ALWAYS AS (json_unquote(json_extract(`BussinessJson`,_utf8mb4'$.FollowFrequency'))) VIRTUAL COMMENT '(AFC)跟进频次(1 高频跟进,2 低频跟进)',
  `v_ReturnedTypeCode` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci GENERATED ALWAYS AS (json_unquote(json_extract(`BussinessJson`,_utf8mb4'$.ReturnedTypeCode'))) VIRTUAL COMMENT '(AFC)还款状态Code（basic_datadictionary.Code)',
  `v_IfRemove` smallint(6) GENERATED ALWAYS AS (json_unquote(json_extract(`BussinessJson`,_utf8mb4'$.IfRemove'))) VIRTUAL COMMENT '(AFC)是否移除（int 0否，1是）',
  `v_FollowFrequencyType` smallint(6) GENERATED ALWAYS AS (json_unquote(json_extract(`BussinessJson`,_utf8mb4'$.FollowFrequencyType'))) VIRTUAL COMMENT '(AFC)跟进频次类型（null&0访后，1访前）',
  `v_AfcCompleteType` smallint(6) GENERATED ALWAYS AS (json_unquote(json_extract(`BussinessJson`,_utf8mb4'$.AfcCompleteType'))) VIRTUAL COMMENT '(AFC)完成类型（0&null否，1手动结束，2正常结束，3超时自动结束）',
  `v_ReportDeadline` datetime GENERATED ALWAYS AS (json_unquote(json_extract(`BussinessJson`,_utf8mb4'$.reportDeadline'))) VIRTUAL COMMENT '(AFC)报告截止时间',
  `v_UnFollowDays` bigint(20) GENERATED ALWAYS AS (json_unquote(json_extract(`BussinessJson`,_utf8mb4'$.UnFollowDays'))) VIRTUAL COMMENT '(AFC)未跟进天数(当前时间-最新谈判记录提交时间-1，若值为-1则置0，超出退案时间不更新）',
  `v_IsRelateEtc` smallint(6) GENERATED ALWAYS AS (json_unquote(json_extract(`BussinessJson`,_utf8mb4'$.IsRelateEtc'))) VIRTUAL COMMENT '(VHS)是否关联ETC工单（1是0否）',
  `v_IfEtcRecord` smallint(6) GENERATED ALWAYS AS (json_unquote(json_extract(`BussinessJson`,_utf8mb4'$.IfEtcRecord'))) VIRTUAL COMMENT '(VHS)关联ETC工单是否备案（1是0否）',
  `v_RescuerName` varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci GENERATED ALWAYS AS (json_unquote(json_extract(`BussinessJson`,_utf8mb4'$.RescuerName'))) VIRTUAL COMMENT '(CHB)救援人姓名',
  `v_RescuerTel` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci GENERATED ALWAYS AS (json_unquote(json_extract(`BussinessJson`,_utf8mb4'$.RescuerTel'))) VIRTUAL COMMENT '(CHB)救援人电话',
  `v_RescuerPlateNumber` varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci GENERATED ALWAYS AS (json_unquote(json_extract(`BussinessJson`,_utf8mb4'$.RescuerPlateNumber'))) VIRTUAL COMMENT '(CHB)救援人车牌号',
  `v_RelateWorkOrderId` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci GENERATED ALWAYS AS (json_unquote(json_extract(`BussinessJson`,_utf8mb4'$.RelateWorkOrderId'))) VIRTUAL COMMENT '(CHB)关联工单Id',
  `DynamicId` varchar(20) NOT NULL DEFAULT 'FA-' COMMENT '动态表单Id',
  `v_DynIsHelpers` varchar(20) GENERATED ALWAYS AS (json_unquote(json_extract(`BussinessJson`,_utf8mb4'$.DynFormInfo.DynIsHelpers'))) VIRTUAL COMMENT '(Dyn)协助人',
  `v_DynVinNumber` varchar(50) GENERATED ALWAYS AS (json_unquote(json_extract(`BussinessJson`,_utf8mb4'$.DynFormInfo.DynVinNumber'))) VIRTUAL COMMENT '(Dyn)车架号',
  `v_OrderRelationId` varchar(36) GENERATED ALWAYS AS (json_unquote(json_extract(`BussinessJson`,_utf8mb4'$.OrderRelationId'))) VIRTUAL COMMENT '(佰信)车务车电关联ID',
  `v_CustNoticeTag` varchar(50) GENERATED ALWAYS AS (json_unquote(json_extract(`BussinessJson`,_utf8mb4'$.CustNoticeTag'))) VIRTUAL COMMENT '(佰信)客户通知标识（0800 放款提交中）',
  `LastUpdateTimeStamp` timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT '最近更新时间',
  `v_IsExtraOrder` int(11) GENERATED ALWAYS AS (json_unquote(json_extract(`BussinessJson`,_utf8mb4'$.IsExtraOrder'))) VIRTUAL COMMENT '(VHS)创收工单标识',
  `v_chpWXAddProgress` varchar(50) GENERATED ALWAYS AS (json_unquote(json_extract(`BussinessJson`,_utf8mb4'$.chpWXAddProgress'))) VIRTUAL COMMENT '(CHP)车主微信添加进度',
  `v_chpCarUserName` varchar(50) GENERATED ALWAYS AS (json_unquote(json_extract(`BussinessJson`,_utf8mb4'$.chpCarUserName'))) VIRTUAL COMMENT '(CHP)车主姓名',
  `v_chpSurveyInstallType` varchar(50) GENERATED ALWAYS AS (json_unquote(json_extract(`BussinessJson`,_utf8mb4'$.chpSurveyInfo.InstallType'))) VIRTUAL COMMENT '(CHP)安装方式',
  `v_chpElectricityMetersType` varchar(50) GENERATED ALWAYS AS (json_unquote(json_extract(`BussinessJson`,_utf8mb4'$.chpSurveyInfo.ElectricityMetersType'))) VIRTUAL COMMENT '(CHP)电表类型',
  `v_chpFirstContactRole` smallint(6) GENERATED ALWAYS AS (if((json_unquote(json_extract(`BussinessJson`,_utf8mb4'$.chpFirstContact.Role')) = _utf8mb4''),0,json_unquote(json_extract(`BussinessJson`,_utf8mb4'$.chpFirstContact.Role')))) VIRTUAL COMMENT '(CHP)首联人角色(1-运营，2-服务人员)',
  `v_chpNextFollowTime` datetime GENERATED ALWAYS AS (if((json_unquote(json_extract(`BussinessJson`,_utf8mb4'$.chpNextFollowTime')) = _utf8mb4''),NULL,if((json_unquote(json_extract(`BussinessJson`,_utf8mb4'$.chpNextFollowTime')) = _utf8mb4'null'),NULL,json_unquote(json_extract(`BussinessJson`,_utf8mb4'$.chpNextFollowTime'))))) VIRTUAL COMMENT '(CHP)下次跟进时间',
  `v_chpCarVinNumber` varchar(100) GENERATED ALWAYS AS (json_unquote(json_extract(`BussinessJson`,_utf8mb4'$.chpCarVinNumber'))) VIRTUAL COMMENT '(CHP)车架号',
  `v_ChpLineActualUsage` int(11) GENERATED ALWAYS AS ((if((json_unquote(json_extract(json_extract(json_unquote(json_extract(`BussinessJson`,_utf8mb4'$.chpAccessories')),json_unquote(json_search(json_unquote(json_extract(`BussinessJson`,_utf8mb4'$.chpAccessories[*].AccessoriesType')),_utf8mb4'one',_utf8mb4'电缆硬线'))),_utf8mb4'$.ActualUsage')) in (_utf8mb4'null',_utf8mb4'')),0,json_unquote(json_extract(json_extract(json_unquote(json_extract(`BussinessJson`,_utf8mb4'$.chpAccessories')),json_unquote(json_search(json_unquote(json_extract(`BussinessJson`,_utf8mb4'$.chpAccessories[*].AccessoriesType')),_utf8mb4'one',_utf8mb4'电缆硬线'))),_utf8mb4'$.ActualUsage'))) + if((json_unquote(json_extract(json_extract(json_unquote(json_extract(`BussinessJson`,_utf8mb4'$.chpAccessories')),json_unquote(json_search(json_unquote(json_extract(`BussinessJson`,_utf8mb4'$.chpAccessories[*].AccessoriesType')),_utf8mb4'one',_utf8mb4'电缆软线'))),_utf8mb4'$.ActualUsage')) in (_utf8mb4'null',_utf8mb4'')),0,json_unquote(json_extract(json_extract(json_unquote(json_extract(`BussinessJson`,_utf8mb4'$.chpAccessories')),json_unquote(json_search(json_unquote(json_extract(`BussinessJson`,_utf8mb4'$.chpAccessories[*].AccessoriesType')),_utf8mb4'one',_utf8mb4'电缆软线'))),_utf8mb4'$.ActualUsage'))))) VIRTUAL COMMENT '(CHP)线缆实际用量（电缆硬线+电缆软线实际用量）',
  `v_chpFactoryBrand` varchar(200) GENERATED ALWAYS AS (json_unquote(json_extract(`BussinessJson`,_utf8mb4'$.chpFactoryBrand'))) VIRTUAL COMMENT '(CHP)主机厂品牌',
  `v_chpActualSolutionCode` varchar(200) GENERATED ALWAYS AS (json_unquote(json_extract(`BussinessJson`,_utf8mb4'$.chpActualSolutionCode'))) VIRTUAL COMMENT '(CHP)实际处理方案Code',
  `v_PostFillWorkOrder` tinyint(3) unsigned GENERATED ALWAYS AS (ifnull(json_unquote(json_extract(`BussinessJson`,_utf8mb4'$.PostFillWorkOrder')),0)) VIRTUAL COMMENT '(车电)后补工单(0-非后补，1-后补工单）',
  `v_chpOrderCompleteTime` datetime GENERATED ALWAYS AS (if((json_unquote(json_extract(`BussinessJson`,_utf8mb4'$.chpOrderCompleteTime')) = _utf8mb4'null'),NULL,json_unquote(json_extract(`BussinessJson`,_utf8mb4'$.chpOrderCompleteTime')))) VIRTUAL COMMENT '(CHP)工单完成时间',
  `v_chpCarUserTel` varchar(50) GENERATED ALWAYS AS (json_unquote(json_extract(`BussinessJson`,_utf8mb4'$.chpCarUserTel'))) VIRTUAL COMMENT '(CHP)车主电话',
  `v_afcAuditPassTime` datetime GENERATED ALWAYS AS (json_unquote(json_extract(`BussinessJson`,_utf8mb4'$.afcAuditPassTime'))) VIRTUAL COMMENT '(AFC)质检通过时间',
  `v_SimYearsStatus` int(11) GENERATED ALWAYS AS (json_unquote(json_extract(`BussinessJson`,_utf8mb4'$.SimYearsStatus'))) VIRTUAL COMMENT '（车电）SIM卡年限是否一致（0否1是）',
  `v_CompleteAging` int(11) GENERATED ALWAYS AS (json_unquote(json_extract(`BussinessJson`,_utf8mb4'$.CompleteAging'))) VIRTUAL COMMENT '完单时效（0不合格 1合格）',
  `v_RescScreenshotAging` int(11) GENERATED ALWAYS AS (json_unquote(json_extract(`BussinessJson`,_utf8mb4'$.RescScreenshotAging'))) VIRTUAL COMMENT '改约截图时效（0不合格 1合格）',
  `v_RescScreenshotResult` int(11) GENERATED ALWAYS AS (json_unquote(json_extract(`BussinessJson`,_utf8mb4'$.RescScreenshotResult'))) VIRTUAL COMMENT '改约截图对比结果（0不合格 1合格）',
  `v_OrderColor` int(11) GENERATED ALWAYS AS (json_unquote(json_extract(`BussinessJson`,_utf8mb4'$.orderColor'))) VIRTUAL COMMENT '(AFC)工单卡片颜色',
  `v_MaxRescScreenshotTime` datetime GENERATED ALWAYS AS (json_unquote(json_extract(`BussinessJson`,_utf8mb4'$.MaxRescScreenshotTime'))) VIRTUAL COMMENT '最大改约有效时间（下单生效时间+工作时间6H（工作时间：8:30-18:00））',
  `v_SecondVisitStatus` int(11) GENERATED ALWAYS AS (json_unquote(json_extract(`BussinessJson`,_utf8mb4'$.SecondVisitStatus'))) VIRTUAL COMMENT '(AFC)二访状态（0-待走访，1-走访中，2-走访完成，3-走访拒绝）',
  `v_SecondVisitTime` datetime GENERATED ALWAYS AS (json_unquote(json_extract(`BussinessJson`,_utf8mb4'$.SecondVisitTime'))) VIRTUAL COMMENT '(AFC)发起二访时间',
  `v_OutCardDate` date GENERATED ALWAYS AS (json_unquote(json_extract(`BussinessJson`,_utf8mb4'$.OutCardDate'))) VIRTUAL COMMENT '(VHS)出证日期',
  `v_LastNegotiatorTime` datetime GENERATED ALWAYS AS (ifnull(json_unquote(json_extract(`BussinessJson`,_utf8mb4'$.LastNegotiatorTime')),json_unquote(json_extract(`BussinessJson`,_utf8mb4'$.NegotiatorTime')))) STORED COMMENT '(AFC)最后一次提交谈判记录时间',
  `v_ToBeAuditTag` smallint(6) GENERATED ALWAYS AS (json_unquote(json_extract(`BussinessJson`,_utf8mb4'$.ToBeAuditTag'))) VIRTUAL COMMENT '(AFC)回款提报待审核标记',
  `v_tirePlateNumber` varchar(20) GENERATED ALWAYS AS (json_unquote(json_extract(`BussinessJson`,_utf8mb4'$.tirePlateNumber'))) VIRTUAL COMMENT '(胎联网)车牌号',
  `v_tireDeviceModel` varchar(200) GENERATED ALWAYS AS (json_unquote(json_extract(`BussinessJson`,_utf8mb4'$.tireDeviceModel'))) VIRTUAL COMMENT '(胎联网)设备型号',
  `v_tireNeedOuterTireRemoval` smallint(6) GENERATED ALWAYS AS (json_unquote(json_extract(`BussinessJson`,_utf8mb4'$.tireNeedOuterTireRemoval'))) VIRTUAL COMMENT '(胎联网)是否需要拆外侧轮胎',
  `v_tireRemovalCount` int(11) GENERATED ALWAYS AS (json_unquote(json_extract(`BussinessJson`,_utf8mb4'$.tireRemovalCount'))) VIRTUAL COMMENT '(胎联网)拆胎数量',
  `v_tireInstallationMethod` varchar(20) GENERATED ALWAYS AS (json_unquote(json_extract(`BussinessJson`,_utf8mb4'$.tireInstallationMethod'))) VIRTUAL COMMENT '(胎联网)安装方式',
  `v_tireReplacementReason` varchar(500) GENERATED ALWAYS AS (json_unquote(json_extract(`BussinessJson`,_utf8mb4'$.tireReplacementReason'))) VIRTUAL COMMENT '(胎联网)更换原因',
  `v_tireRemovalReason` varchar(500) GENERATED ALWAYS AS (json_unquote(json_extract(`BussinessJson`,_utf8mb4'$.tireRemovalReason'))) VIRTUAL COMMENT '(胎联网)拆回原因',
  `v_tireReplacementRemovalReason` varchar(500) GENERATED ALWAYS AS (json_unquote(json_extract(`BussinessJson`,_utf8mb4'$.tireReplacementRemovalReason'))) VIRTUAL COMMENT '(胎联网)更换拆回原因',
  `v_tirePosition` varchar(50) GENERATED ALWAYS AS (json_unquote(json_extract(`BussinessJson`,_utf8mb4'$.tirePosition'))) VIRTUAL COMMENT '(胎联网)轮胎轮位',
  `v_tireNumber` varchar(50) GENERATED ALWAYS AS (json_unquote(json_extract(`BussinessJson`,_utf8mb4'$.tireNumber'))) VIRTUAL COMMENT '(胎联网)胎号',
  `v_tirePositionChangeReason` varchar(50) GENERATED ALWAYS AS (json_unquote(json_extract(`BussinessJson`,_utf8mb4'$.tirePositionChangeReason'))) VIRTUAL COMMENT '(胎联网)换位原因',
  `v_tirePositionChangeSuggestion` varchar(50) GENERATED ALWAYS AS (json_unquote(json_extract(`BussinessJson`,_utf8mb4'$.tirePositionChangeSuggestion'))) VIRTUAL COMMENT '(胎联网)换位建议',
  `v_tireInflationPosition` varchar(50) GENERATED ALWAYS AS (json_unquote(json_extract(`BussinessJson`,_utf8mb4'$.tireInflationPosition'))) VIRTUAL COMMENT '(胎联网)充气轮胎轮位',
  `v_tirePressure` varchar(50) GENERATED ALWAYS AS (json_unquote(json_extract(`BussinessJson`,_utf8mb4'$.tirePressure'))) VIRTUAL COMMENT '(胎联网)胎压',
  `v_tireRemovalInstallationPosition` varchar(50) GENERATED ALWAYS AS (json_unquote(json_extract(`BussinessJson`,_utf8mb4'$.tireRemovalInstallationPosition'))) VIRTUAL COMMENT '(胎联网)拆装轮胎轮位',
  `v_tireInspectedVehicleCount` varchar(50) GENERATED ALWAYS AS (json_unquote(json_extract(`BussinessJson`,_utf8mb4'$.tireInspectedVehicleCount'))) VIRTUAL COMMENT '(胎联网)巡检车辆数量',
  `v_tireIsSupplementaryOrder` smallint(6) GENERATED ALWAYS AS (json_unquote(json_extract(`BussinessJson`,_utf8mb4'$.tireIsSupplementaryOrder'))) VIRTUAL COMMENT '(胎联网)是否后补工单(0否 1是)',
  `v_tireRepairTypeId` varchar(20) GENERATED ALWAYS AS (json_unquote(json_extract(`BussinessJson`,_utf8mb4'$.tireRepairTypeId'))) VIRTUAL COMMENT '(胎联网)修复方式Id(basic_datadictionary.Id)',
  `v_tireRepairTypeName` varchar(20) GENERATED ALWAYS AS (json_unquote(json_extract(`BussinessJson`,_utf8mb4'$.tireRepairTypeName'))) VIRTUAL COMMENT '(胎联网)修复方式Id(basic_datadictionary.Name)',
  `v_need_reinstall` varchar(50) GENERATED ALWAYS AS (json_unquote(json_extract(json_extract(`BussinessJson`,_utf8mb4'$.ExtraFields'),_utf8mb4'$.need_reinstall'))) VIRTUAL COMMENT '(车电)是否更换设备--民生',
  `v_chpCarModel` varchar(50) GENERATED ALWAYS AS (json_unquote(json_extract(`BussinessJson`,_utf8mb4'$.chpCarModel'))) VIRTUAL COMMENT '(CHP)车型',
  `v_CustomerAuditStatus` int(11) GENERATED ALWAYS AS (json_unquote(json_extract(`BussinessJson`,_utf8mb4'$.CustomerAuditStatus'))) VIRTUAL COMMENT '客户审核状态',
  `v_SelfOperatedInstallId` varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci GENERATED ALWAYS AS (json_unquote(json_extract(`BussinessJson`,_utf8mb4'$.SelfOperatedInstallId'))) VIRTUAL COMMENT '(车电)自营安装工单 ID',
  PRIMARY KEY (`Id`,`DynamicId`),
  KEY `NON-WorkOrderId` (`WorkOrderId`),
  KEY `NON-DynamicId` (`DynamicId`) USING BTREE,
  KEY `NON-LastUpdateTimeStamp` (`LastUpdateTimeStamp`),
  KEY `NON-ReturnedTypeCode` (`v_ReturnedTypeCode`),
  KEY `NON-FollowFrequency` (`v_FollowFrequency`),
  KEY `NON-AppointTime` (`appointTime`),
  KEY `NON_RescuerTel` (`v_RescuerTel`),
  KEY `NON-IsRelateEtc` (`v_IsRelateEtc`),
  KEY `NON_RescuerPlateNumber` (`v_RescuerPlateNumber`),
  KEY `NON-RelateWorkOrderId` (`v_RelateWorkOrderId`),
  KEY `NON-IfEtcRecord` (`v_IfEtcRecord`),
  KEY `NON-FollowFrequencyType` (`v_FollowFrequencyType`),
  KEY `NON_RescuerName` (`v_RescuerName`),
  KEY `NON-ReportDeadline` (`v_ReportDeadline`),
  KEY `NON-UnFollowDays` (`v_UnFollowDays`),
  KEY `NON-AppraisalStatus` (`AppraisalStatus`),
  KEY `NON-IfRemove` (`v_IfRemove`),
  KEY `NON-AfcCompleteType` (`v_AfcCompleteType`),
  KEY `NON-DynIsHelpers` (`v_DynIsHelpers`),
  KEY `NON-DynVinNumber` (`v_DynVinNumber`),
  KEY `NON-v_OrderRelationId` (`v_OrderRelationId`),
  KEY `NON-v_IsExtraOrder` (`v_IsExtraOrder`) USING BTREE,
  KEY `NON-v_chpWXAddProgress` (`v_chpWXAddProgress`) USING BTREE,
  KEY `NON-v_chpCarUserName` (`v_chpCarUserName`) USING BTREE,
  KEY `NON-v_chpSurveyInstallType` (`v_chpSurveyInstallType`) USING BTREE,
  KEY `NON-v_chpElectricityMetersType` (`v_chpElectricityMetersType`) USING BTREE,
  KEY `NON-v_chpFirstContactRole` (`v_chpFirstContactRole`) USING BTREE,
  KEY `NON-v_chpNextFollowTime` (`v_chpNextFollowTime`) USING BTREE,
  KEY `NON-v_chpCarVinNumber` (`v_chpCarVinNumber`) USING BTREE,
  KEY `NON-v_chpFactoryBrand` (`v_chpFactoryBrand`),
  KEY `NON-v_chpActualSolutionCode` (`v_chpActualSolutionCode`),
  KEY `NON-v_PostFillWorkOrder` (`v_PostFillWorkOrder`),
  KEY `NON-chpOrderCompleteTime` (`v_chpOrderCompleteTime`),
  KEY `NON-chpCarUserTel` (`v_chpCarUserTel`),
  KEY `v_afcAuditPassTime` (`v_afcAuditPassTime`),
  KEY `SimYearsStatus` (`v_SimYearsStatus`),
  KEY `NON-v_CompleteAging` (`v_CompleteAging`),
  KEY `NON-v_RescScreenshotAging` (`v_RescScreenshotAging`),
  KEY `NON-v_RescScreenshotResult` (`v_RescScreenshotResult`),
  KEY `v_OrderColor` (`v_OrderColor`),
  KEY `NON-v_MaxRescScreenshotTime` (`v_MaxRescScreenshotTime`),
  KEY `NON-v_SecondVisitStatus` (`v_SecondVisitStatus`),
  KEY `NON-v_SecondVisitTime` (`v_SecondVisitTime`),
  KEY `NON-v_OutCardDate` (`v_OutCardDate`),
  KEY `NON-v_need_reinstall` (`v_need_reinstall`) USING BTREE,
  KEY `NON-v_CustomerAuditStatus` (`v_CustomerAuditStatus`) USING BTREE,
  KEY `NON-v_SelfOperatedInstallId` (`v_SelfOperatedInstallId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 ROW_FORMAT=DYNAMIC COMMENT='业务域_工单业务信息JOSN冗余表'
;

INSERT INTO serviceordercenterhis.tb_workbussinessjsoninfo(Id,WorkOrderId,BussinessJson,InsertTime,Deleted)
SELECT
  Id,
  WorkOrderId,
  CASE
    WHEN json_unquote(json_extract(BussinessJson,'$.tireNeedOuterTireRemoval')) IN ('','null')
      THEN json_remove(BussinessJson,'$.tireNeedOuterTireRemoval')
    ELSE BussinessJson
  END AS BussinessJson,
  InsertTime,
  Deleted
FROM serviceordercenter.tb_workbussinessjsoninfo;
