DROP TABLE IF EXISTS serviceordercenterhistest.tb_feeapplicationinfo;
CREATE TABLE serviceordercenterhistest.`tb_feeapplicationinfo` (
  `Id` char(12) NOT NULL COMMENT '费用申请信息主键(FE)',
  `TargetId` char(12) DEFAULT NULL COMMENT '工单主单主键(tb_workorderinfo.Id)',
  `OrgCode` varchar(50) DEFAULT NULL COMMENT '组织编码（1001车电 1002金融 1003车务 1000平台）',
  `FeeGroupCode` varchar(50) DEFAULT NULL COMMENT '费用标准组Code',
  `AuditStatus` smallint(6) DEFAULT NULL COMMENT '审核状态（0已撤回 1待审核 2审核通过 3审核拒绝）',
  `FeeItemId` varchar(12) DEFAULT NULL COMMENT '费用配置项主键(tb_feeiteminfo.Id)',
  `FeeValue` decimal(16,2) DEFAULT NULL COMMENT '费用值',
  `ApplyFee` decimal(16,2) DEFAULT NULL COMMENT '申请金额',
  `FeeApplyTime` datetime DEFAULT NULL COMMENT '费用申请时间',
  `ApplyWorkStatus` int(11) DEFAULT NULL COMMENT '申请时工单状态',
  `SubsidyStatus` smallint(6) DEFAULT NULL COMMENT '发放状态(0未发放 1已发放）',
  `SubsidyTime` datetime DEFAULT NULL COMMENT '发放时间',
  `SubsidyRemark` varchar(200) DEFAULT NULL COMMENT '发放备注',
  `SubsidyLoginName` varchar(50) DEFAULT NULL COMMENT '发放人账号',
  `SubsidyName` varchar(100) DEFAULT NULL COMMENT '发放人姓名',
  `ApplyPersonCode` varchar(50) DEFAULT NULL COMMENT '申请人Code',
  `ApplyPersonName` varchar(100) DEFAULT NULL COMMENT '申请人姓名',
  `ApplyReason` varchar(300) DEFAULT NULL COMMENT '申请原因',
  `PayeeCode` varchar(50) DEFAULT NULL COMMENT '收款人工号',
  `PayeeName` varchar(100) DEFAULT NULL COMMENT '收款人姓名',
  `OriginalPayeeCode` varchar(50) DEFAULT NULL COMMENT '收款人工号(原)',
  `OriginalPayeeName` varchar(100) DEFAULT NULL COMMENT '收款人姓名(原)',
  `LastAuditPersonCode` varchar(50) DEFAULT NULL COMMENT '审核人Code(最新)',
  `LastAuditPersonName` varchar(100) DEFAULT NULL COMMENT '审核人姓名(最新)',
  `LastAuditTime` datetime DEFAULT NULL COMMENT '最新审核时间',
  `AuditRemark` varchar(200) DEFAULT NULL COMMENT '审核备注',
  `RuleActionLogId` varchar(12) DEFAULT NULL COMMENT '规则操作日志ID(common_ruleactionlog.Id)',
  `ExtraJson` json DEFAULT NULL COMMENT '费用额外信息(AccommodationTime住宿时间 CalculationMethod计算方式 SettleMethod人员自定义属性-服务商结算方式（CHP））',
  `DynamicFormJson` json DEFAULT NULL COMMENT '动态表单内容json',
  `v_SettleMethod` varchar(10) GENERATED ALWAYS AS (json_unquote(json_extract(`ExtraJson`,_utf8mb4'$.SettleMethod'))) VIRTUAL COMMENT '人员自定义属性-服务商结算方式（CHP）',
  `InsertTime` datetime DEFAULT NULL,
  `Deleted` tinyint(1) NOT NULL,
  PRIMARY KEY (`Id`),
  KEY `NON-TargetId` (`TargetId`) USING BTREE,
  KEY `NON-OrgCode` (`OrgCode`) USING BTREE,
  KEY `NON-FeeItemId` (`FeeItemId`) USING BTREE,
  KEY `NON-FeeApplyTime` (`FeeApplyTime`) USING BTREE,
  KEY `NON-ApplyPersonCode` (`ApplyPersonCode`),
  KEY `NON-PayeeCode` (`PayeeCode`) USING BTREE,
  KEY `NON-LastAuditPersonCode` (`LastAuditPersonCode`) USING BTREE,
  KEY `NON-LastAuditTime` (`LastAuditTime`) USING BTREE,
  KEY `NON-SubsidyStatus` (`SubsidyStatus`) USING BTREE,
  KEY `NON-AuditStatus` (`AuditStatus`) USING BTREE,
  KEY `NON-RuleActionLogId` (`RuleActionLogId`) USING BTREE,
  KEY `SubsidyTime` (`SubsidyTime` DESC),
  KEY `FeeGroupCode` (`FeeGroupCode`),
  KEY `SettleMethod` (`v_SettleMethod`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='通用域_费用申请明细表'
;

INSERT INTO serviceordercenterhistest.tb_feeapplicationinfo(`Id`, `TargetId`, `OrgCode`, `FeeGroupCode`, `AuditStatus`, `FeeItemId`, `FeeValue`, `ApplyFee`, `FeeApplyTime`, `ApplyWorkStatus`, `SubsidyStatus`, `SubsidyTime`, `SubsidyRemark`, `SubsidyLoginName`, `SubsidyName`, `ApplyPersonCode`, `ApplyPersonName`, `ApplyReason`, `PayeeCode`, `PayeeName`, `OriginalPayeeCode`, `OriginalPayeeName`, `LastAuditPersonCode`, `LastAuditPersonName`, `LastAuditTime`, `AuditRemark`, `RuleActionLogId`, `ExtraJson`, `DynamicFormJson`, `InsertTime`, `Deleted`)
SELECT `Id`, `TargetId`, `OrgCode`, `FeeGroupCode`, `AuditStatus`, `FeeItemId`, `FeeValue`, `ApplyFee`, `FeeApplyTime`, `ApplyWorkStatus`, `SubsidyStatus`, `SubsidyTime`, `SubsidyRemark`, `SubsidyLoginName`, `SubsidyName`, `ApplyPersonCode`, `ApplyPersonName`, `ApplyReason`, `PayeeCode`, `PayeeName`, `OriginalPayeeCode`, `OriginalPayeeName`, `LastAuditPersonCode`, `LastAuditPersonName`, `LastAuditTime`, `AuditRemark`, `RuleActionLogId`, `ExtraJson`, `DynamicFormJson`, `InsertTime`, `Deleted`
FROM serviceordercenter.tb_feeapplicationinfo;

DROP TABLE IF EXISTS serviceordercenterhistest.tb_workflowjsoninfo;
CREATE TABLE serviceordercenterhistest.`tb_workflowjsoninfo` (
  `Id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '自增Id',
  `WorkOrderId` char(12) DEFAULT NULL COMMENT '工单主单主键(tb_workorderinfo.Id)',
  `RuntimeItemId` varchar(36) DEFAULT NULL COMMENT '工作流主键(workflowruntimeitems.id/workflowcompleteitems.Id)',
  `StepJson` json DEFAULT NULL,
  `SourceMode` smallint(6) NOT NULL DEFAULT '1' COMMENT '步骤数据生成方式(1程序生成2过程初始化3手动修正)',
  `InsertTime` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `Deleted` tinyint(1) NOT NULL DEFAULT (0),
  `v_FirstAssignTime` datetime GENERATED ALWAYS AS (ifnull(json_unquote(json_extract(`StepJson`,_utf8mb4'$.TCW001.FST')),ifnull(json_unquote(json_extract(`StepJson`,_utf8mb4'$.THWC010.FST')),ifnull(json_unquote(json_extract(`StepJson`,_utf8mb4'$.TDismantleCode002.FST')),ifnull(json_unquote(json_extract(`StepJson`,_utf8mb4'$.TSwitchCode002.FST')),ifnull(json_unquote(json_extract(`StepJson`,_utf8mb4'$.TMultiple001_Distribute.FST')),ifnull(json_unquote(json_extract(`StepJson`,_utf8mb4'$.TCheckCar010.FST')),ifnull(json_unquote(json_extract(`StepJson`,_utf8mb4'$.TInstallNonSelf001.FST')),ifnull(json_unquote(json_extract(`StepJson`,_utf8mb4'$.TOverhaulCode002.FST')),NULL))))))))) VIRTUAL,
  `v_FirstRecordTime` datetime GENERATED ALWAYS AS (ifnull(json_unquote(json_extract(`StepJson`,_utf8mb4'$.TFinanceService007.FAT')),ifnull(json_unquote(json_extract(`StepJson`,_utf8mb4'$.THWC030.FAT')),ifnull(json_unquote(json_extract(`StepJson`,_utf8mb4'$.TOverhaulCode004.FAT')),ifnull(json_unquote(json_extract(`StepJson`,_utf8mb4'$.TDismantleCode004.FAT')),ifnull(json_unquote(json_extract(`StepJson`,_utf8mb4'$.TSwitchCode004.FAT')),ifnull(json_unquote(json_extract(`StepJson`,_utf8mb4'$.TMultiple001_Record.FAT')),ifnull(json_unquote(json_extract(`StepJson`,_utf8mb4'$.TCW004.FAT')),ifnull(json_unquote(json_extract(`StepJson`,_utf8mb4'$.TCheckCar030.FAT')),ifnull(json_unquote(json_extract(`StepJson`,_utf8mb4'$.TOverhaulNonSelf003.FAT')),ifnull(json_unquote(json_extract(`StepJson`,_utf8mb4'$.TInstallNonSelf003.FAT')),ifnull(json_unquote(json_extract(`StepJson`,_utf8mb4'$.TBeforeLoan008.FAT')),NULL)))))))))))) VIRTUAL,
  `v_FirstRecordPersonCode` varchar(100) CHARACTER SET utf8 COLLATE utf8_general_ci GENERATED ALWAYS AS (ifnull(json_unquote(json_extract(`StepJson`,_utf8mb4'$.PFinanceService007.FAP')),ifnull(json_unquote(json_extract(`StepJson`,_utf8mb4'$.PHWC030.FAP')),ifnull(json_unquote(json_extract(`StepJson`,_utf8mb4'$.POverhaulCode004.FAP')),ifnull(json_unquote(json_extract(`StepJson`,_utf8mb4'$.PDismantleCode004.FAP')),ifnull(json_unquote(json_extract(`StepJson`,_utf8mb4'$.PSwitchCode004.FAP')),ifnull(json_unquote(json_extract(`StepJson`,_utf8mb4'$.PMultiple001_Record.FAP')),ifnull(json_unquote(json_extract(`StepJson`,_utf8mb4'$.PCW004.FAP')),ifnull(json_unquote(json_extract(`StepJson`,_utf8mb4'$.PCheckCar030.FAP')),ifnull(json_unquote(json_extract(`StepJson`,_utf8mb4'$.POverhaulNonSelf003.FAP')),ifnull(json_unquote(json_extract(`StepJson`,_utf8mb4'$.PInstallNonSelf003.FAP')),ifnull(json_unquote(json_extract(`StepJson`,_utf8mb4'$.PBeforeLoan008.FAP')),NULL)))))))))))) VIRTUAL,
  `v_FirstRecordPersonName` varchar(100) CHARACTER SET utf8 COLLATE utf8_general_ci GENERATED ALWAYS AS (ifnull(json_unquote(json_extract(`StepJson`,_utf8mb4'$.NFinanceService007.FAN')),ifnull(json_unquote(json_extract(`StepJson`,_utf8mb4'$.NHWC030.FAN')),ifnull(json_unquote(json_extract(`StepJson`,_utf8mb4'$.NOverhaulCode004.FAN')),ifnull(json_unquote(json_extract(`StepJson`,_utf8mb4'$.NDismantleCode004.FAN')),ifnull(json_unquote(json_extract(`StepJson`,_utf8mb4'$.NSwitchCode004.FAN')),ifnull(json_unquote(json_extract(`StepJson`,_utf8mb4'$.NMultiple001_Record.FAN')),ifnull(json_unquote(json_extract(`StepJson`,_utf8mb4'$.NCW004.FAN')),ifnull(json_unquote(json_extract(`StepJson`,_utf8mb4'$.NCheckCar030.FAN')),ifnull(json_unquote(json_extract(`StepJson`,_utf8mb4'$.NOverhaulNonSelf003.FAN')),ifnull(json_unquote(json_extract(`StepJson`,_utf8mb4'$.NInstallNonSelf003.FAN')),ifnull(json_unquote(json_extract(`StepJson`,_utf8mb4'$.NBeforeLoan008.FAN')),NULL)))))))))))) VIRTUAL,
  `v_FirstAuditTime` datetime GENERATED ALWAYS AS (ifnull(json_unquote(json_extract(`StepJson`,_utf8mb4'$.TFinanceService008.FAT')),ifnull(json_unquote(json_extract(`StepJson`,_utf8mb4'$.THWC050.FAT')),ifnull(json_unquote(json_extract(`StepJson`,_utf8mb4'$.TOverhaulNonSelf004.FAT')),ifnull(json_unquote(json_extract(`StepJson`,_utf8mb4'$.TMultiple001_Audit.FAT')),ifnull(json_unquote(json_extract(`StepJson`,_utf8mb4'$.TCW005.FAT')),ifnull(json_unquote(json_extract(`StepJson`,_utf8mb4'$.TBeforeLoan009.FAT')),NULL))))))) VIRTUAL,
  `v_FirstAuditPersonCode` varchar(100) CHARACTER SET utf8 COLLATE utf8_general_ci GENERATED ALWAYS AS (ifnull(json_unquote(json_extract(`StepJson`,_utf8mb4'$.PFinanceService008.FAP')),ifnull(json_unquote(json_extract(`StepJson`,_utf8mb4'$.PHWC050.FAP')),ifnull(json_unquote(json_extract(`StepJson`,_utf8mb4'$.POverhaulNonSelf004.FAP')),ifnull(json_unquote(json_extract(`StepJson`,_utf8mb4'$.PMultiple001_Audit.FAP')),ifnull(json_unquote(json_extract(`StepJson`,_utf8mb4'$.PCW005.FAP')),ifnull(json_unquote(json_extract(`StepJson`,_utf8mb4'$.PBeforeLoan009.FAP')),NULL))))))) VIRTUAL,
  `v_FirstAuditPersonName` varchar(100) CHARACTER SET utf8 COLLATE utf8_general_ci GENERATED ALWAYS AS (ifnull(json_unquote(json_extract(`StepJson`,_utf8mb4'$.NFinanceService008.FAN')),ifnull(json_unquote(json_extract(`StepJson`,_utf8mb4'$.NHWC050.FAN')),ifnull(json_unquote(json_extract(`StepJson`,_utf8mb4'$.NOverhaulNonSelf004.FAN')),ifnull(json_unquote(json_extract(`StepJson`,_utf8mb4'$.NMultiple001_Audit.FAN')),ifnull(json_unquote(json_extract(`StepJson`,_utf8mb4'$.NCW005.FAN')),ifnull(json_unquote(json_extract(`StepJson`,_utf8mb4'$.NBeforeLoan009.FAN')),NULL))))))) VIRTUAL,
  `v_LastAuditTime` datetime GENERATED ALWAYS AS (ifnull(json_unquote(json_extract(`StepJson`,_utf8mb4'$.TFinanceService008.LAT')),ifnull(json_unquote(json_extract(`StepJson`,_utf8mb4'$.THWC050.LAT')),ifnull(json_unquote(json_extract(`StepJson`,_utf8mb4'$.TOverhaulNonSelf004.LAT')),ifnull(json_unquote(json_extract(`StepJson`,_utf8mb4'$.TMultiple001_Audit.LAT')),ifnull(json_unquote(json_extract(`StepJson`,_utf8mb4'$.TCW005.LAT')),ifnull(json_unquote(json_extract(`StepJson`,_utf8mb4'$.TBeforeLoan009.LAT')),NULL))))))) VIRTUAL,
  `v_LastAuditPersonCode` varchar(100) CHARACTER SET utf8 COLLATE utf8_general_ci GENERATED ALWAYS AS (ifnull(json_unquote(json_extract(`StepJson`,_utf8mb4'$.PFinanceService008.LAP')),ifnull(json_unquote(json_extract(`StepJson`,_utf8mb4'$.PHWC050.LAP')),ifnull(json_unquote(json_extract(`StepJson`,_utf8mb4'$.POverhaulNonSelf004.LAP')),ifnull(json_unquote(json_extract(`StepJson`,_utf8mb4'$.PMultiple001_Audit.LAP')),ifnull(json_unquote(json_extract(`StepJson`,_utf8mb4'$.PCW005.LAP')),ifnull(json_unquote(json_extract(`StepJson`,_utf8mb4'$.PBeforeLoan009.LAP')),NULL))))))) VIRTUAL,
  `v_LastAuditPersonName` varchar(100) CHARACTER SET utf8 COLLATE utf8_general_ci GENERATED ALWAYS AS (ifnull(json_unquote(json_extract(`StepJson`,_utf8mb4'$.NFinanceService008.LAN')),ifnull(json_unquote(json_extract(`StepJson`,_utf8mb4'$.NHWC050.LAN')),ifnull(json_unquote(json_extract(`StepJson`,_utf8mb4'$.NOverhaulNonSelf004.LAN')),ifnull(json_unquote(json_extract(`StepJson`,_utf8mb4'$.NMultiple001_Audit.LAN')),ifnull(json_unquote(json_extract(`StepJson`,_utf8mb4'$.NCW005.LAN')),ifnull(json_unquote(json_extract(`StepJson`,_utf8mb4'$.NBeforeLoan009.LAN')),NULL))))))) VIRTUAL,
  `v_FirstCustAuditTime` datetime GENERATED ALWAYS AS (ifnull(json_unquote(json_extract(`StepJson`,_utf8mb4'$.TOverhaulNonSelf006.FAT')),ifnull(json_unquote(json_extract(`StepJson`,_utf8mb4'$.TMultiple001_CustAudit.FAT')),ifnull(json_unquote(json_extract(`StepJson`,_utf8mb4'$.THWC040.FAT')),ifnull(json_unquote(json_extract(`StepJson`,_utf8mb4'$.TMultiple001_Audit.FAT')),ifnull(json_unquote(json_extract(`StepJson`,_utf8mb4'$.TOverhaulCode005.FAT')),NULL)))))) VIRTUAL,
  `v_FirstCustAuditPersonCode` varchar(100) CHARACTER SET utf8 COLLATE utf8_general_ci GENERATED ALWAYS AS (ifnull(json_unquote(json_extract(`StepJson`,_utf8mb4'$.POverhaulNonSelf006.FAP')),ifnull(json_unquote(json_extract(`StepJson`,_utf8mb4'$.PMultiple001_CustAudit.FAP')),ifnull(json_unquote(json_extract(`StepJson`,_utf8mb4'$.PHWC040.FAP')),ifnull(json_unquote(json_extract(`StepJson`,_utf8mb4'$.PMultiple001_Audit.FAP')),ifnull(json_unquote(json_extract(`StepJson`,_utf8mb4'$.POverhaulCode005.FAP')),NULL)))))) VIRTUAL,
  `v_FirstCustAuditPersonName` varchar(100) CHARACTER SET utf8 COLLATE utf8_general_ci GENERATED ALWAYS AS (ifnull(json_unquote(json_extract(`StepJson`,_utf8mb4'$.NOverhaulNonSelf006.FAN')),ifnull(json_unquote(json_extract(`StepJson`,_utf8mb4'$.NMultiple001_CustAudit.FAN')),ifnull(json_unquote(json_extract(`StepJson`,_utf8mb4'$.NHWC040.FAN')),ifnull(json_unquote(json_extract(`StepJson`,_utf8mb4'$.NMultiple001_Audit.FAN')),ifnull(json_unquote(json_extract(`StepJson`,_utf8mb4'$.NOverhaulCode005.FAN')),NULL)))))) VIRTUAL,
  `v_LastCustAuditTime` datetime GENERATED ALWAYS AS (ifnull(json_unquote(json_extract(`StepJson`,_utf8mb4'$.TOverhaulNonSelf006.LAT')),ifnull(json_unquote(json_extract(`StepJson`,_utf8mb4'$.TMultiple001_CustAudit.LAT')),ifnull(json_unquote(json_extract(`StepJson`,_utf8mb4'$.THWC040.LAT')),ifnull(json_unquote(json_extract(`StepJson`,_utf8mb4'$.TMultiple001_Audit.LAT')),ifnull(json_unquote(json_extract(`StepJson`,_utf8mb4'$.TOverhaulCode005.LAT')),NULL)))))) VIRTUAL,
  `v_LastCustAuditPersonCode` varchar(100) CHARACTER SET utf8 COLLATE utf8_general_ci GENERATED ALWAYS AS (ifnull(json_unquote(json_extract(`StepJson`,_utf8mb4'$.POverhaulNonSelf006.LAP')),ifnull(json_unquote(json_extract(`StepJson`,_utf8mb4'$.PMultiple001_CustAudit.LAP')),ifnull(json_unquote(json_extract(`StepJson`,_utf8mb4'$.PHWC040.LAP')),ifnull(json_unquote(json_extract(`StepJson`,_utf8mb4'$.PMultiple001_Audit.LAP')),ifnull(json_unquote(json_extract(`StepJson`,_utf8mb4'$.POverhaulCode005.LAP')),NULL)))))) VIRTUAL,
  `v_LastCustAuditPersonName` varchar(100) CHARACTER SET utf8 COLLATE utf8_general_ci GENERATED ALWAYS AS (ifnull(json_unquote(json_extract(`StepJson`,_utf8mb4'$.NOverhaulNonSelf006.LAN')),ifnull(json_unquote(json_extract(`StepJson`,_utf8mb4'$.NMultiple001_CustAudit.LAN')),ifnull(json_unquote(json_extract(`StepJson`,_utf8mb4'$.NHWC040.LAN')),ifnull(json_unquote(json_extract(`StepJson`,_utf8mb4'$.NMultiple001_Audit.LAN')),ifnull(json_unquote(json_extract(`StepJson`,_utf8mb4'$.NOverhaulCode005.LAN')),NULL)))))) VIRTUAL,
  `v_LastRecordTime` datetime GENERATED ALWAYS AS (ifnull(json_unquote(json_extract(`StepJson`,_utf8mb4'$.TOverhaulNonSelf003.LAT')),ifnull(json_unquote(json_extract(`StepJson`,_utf8mb4'$.TOverhaulNonSelf007.LAT')),ifnull(json_unquote(json_extract(`StepJson`,_utf8mb4'$.Code1067009.LAT')),ifnull(json_unquote(json_extract(`StepJson`,_utf8mb4'$.Code1067011.LAT')),ifnull(json_unquote(json_extract(`StepJson`,_utf8mb4'$.Code1067006.LAT')),ifnull(json_unquote(json_extract(`StepJson`,_utf8mb4'$.Code1067003.LAT')),ifnull(json_unquote(json_extract(`StepJson`,_utf8mb4'$.THWC030_RE.LAT')),ifnull(json_unquote(json_extract(`StepJson`,_utf8mb4'$.THWC030_RE.LAT')),ifnull(json_unquote(json_extract(`StepJson`,_utf8mb4'$.TCarHornbill006.LAT')),ifnull(json_unquote(json_extract(`StepJson`,_utf8mb4'$.TFinanceService007.LAT')),ifnull(json_unquote(json_extract(`StepJson`,_utf8mb4'$.TDismantleCode004.LAT')),ifnull(json_unquote(json_extract(`StepJson`,_utf8mb4'$.TDismantleCode007.LAT')),ifnull(json_unquote(json_extract(`StepJson`,_utf8mb4'$.TCW004.LAT')),ifnull(json_unquote(json_extract(`StepJson`,_utf8mb4'$.TOverhaulCode004.LAT')),ifnull(json_unquote(json_extract(`StepJson`,_utf8mb4'$.TOverhaulCode007.LAT')),ifnull(json_unquote(json_extract(`StepJson`,_utf8mb4'$.TCheckCar030.LAT')),ifnull(json_unquote(json_extract(`StepJson`,_utf8mb4'$.TDismantleNonSelf007.LAT')),ifnull(json_unquote(json_extract(`StepJson`,_utf8mb4'$.TDismantleNonSelf003.LAT')),ifnull(json_unquote(json_extract(`StepJson`,_utf8mb4'$.TInstallNonSelf007.LAT')),ifnull(json_unquote(json_extract(`StepJson`,_utf8mb4'$.TInstallNonSelf003.LAT')),ifnull(json_unquote(json_extract(`StepJson`,_utf8mb4'$.TInstallNonSelf001.LAT')),ifnull(json_unquote(json_extract(`StepJson`,_utf8mb4'$.TBeforeLoan008.LAT')),ifnull(json_unquote(json_extract(`StepJson`,_utf8mb4'$.TMultiple001_Record.LAT')),ifnull(json_unquote(json_extract(`StepJson`,_utf8mb4'$.TSwitchCode004.LAT')),ifnull(json_unquote(json_extract(`StepJson`,_utf8mb4'$.TSwitchCode008.LAT')),ifnull(json_unquote(json_extract(`StepJson`,_utf8mb4'$.TSwitchNonSelf007.LAT')),ifnull(json_unquote(json_extract(`StepJson`,_utf8mb4'$.TSwitchNonSelf003.LAT')),ifnull(json_unquote(json_extract(`StepJson`,_utf8mb4'$.TVehicleBus_03.LAT')),NULL))))))))))))))))))))))))))))) VIRTUAL COMMENT '最后一次备案时间',
  `v_OrderCompleteTime` datetime GENERATED ALWAYS AS (ifnull(json_unquote(json_extract(`StepJson`,_utf8mb4'$.TInstall001_End.LST')),ifnull(json_unquote(json_extract(`StepJson`,_utf8mb4'$.TPadPasting001_End.LST')),ifnull(json_unquote(json_extract(`StepJson`,_utf8mb4'$.TCarHornbill001_End.LST')),ifnull(json_unquote(json_extract(`StepJson`,_utf8mb4'$.TDismantle001_End.LST')),ifnull(json_unquote(json_extract(`StepJson`,_utf8mb4'$.TBeforeLoan_End.LST')),ifnull(json_unquote(json_extract(`StepJson`,_utf8mb4'$.TCarAgentETC_End.LST')),ifnull(json_unquote(json_extract(`StepJson`,_utf8mb4'$.TCarAgent001_End.LST')),ifnull(json_unquote(json_extract(`StepJson`,_utf8mb4'$.TFinanceServiceVisit_End.LST')),ifnull(json_unquote(json_extract(`StepJson`,_utf8mb4'$.TCheckCar001_End.LST')),ifnull(json_unquote(json_extract(`StepJson`,_utf8mb4'$.TSwitch001_End.LST')),ifnull(json_unquote(json_extract(`StepJson`,_utf8mb4'$.TInstall001_End.LST')),ifnull(json_unquote(json_extract(`StepJson`,_utf8mb4'$.TDismantle001_End.LST')),ifnull(json_unquote(json_extract(`StepJson`,_utf8mb4'$.TMultiple001_End.LST')),ifnull(json_unquote(json_extract(`StepJson`,_utf8mb4'$.TChpInstall001_End.LST')),ifnull(json_unquote(json_extract(`StepJson`,_utf8mb4'$.TOverhaulOrderMesPush_End.LST')),ifnull(json_unquote(json_extract(`StepJson`,_utf8mb4'$.TFinanceServiceVisit_End.LST')),ifnull(json_unquote(json_extract(`StepJson`,_utf8mb4'$.TChpAfterSales_End.LST')),ifnull(json_unquote(json_extract(`StepJson`,_utf8mb4'$.TZRSC002_End.LST')),ifnull(json_unquote(json_extract(`StepJson`,_utf8mb4'$.TDismantleOrderMesPush_End.LST')),ifnull(json_unquote(json_extract(`StepJson`,_utf8mb4'$.TVehicleBus001_End.LST')),ifnull(json_unquote(json_extract(`StepJson`,_utf8mb4'$.TOverhaul001_End.LST')),NULL)))))))))))))))))))))) VIRTUAL COMMENT '工单完成时间',
  `v_FirstDistributeTime` datetime GENERATED ALWAYS AS (ifnull(json_unquote(json_extract(`StepJson`,_utf8mb4'$.TOverhaulNonSelf001.FAT')),ifnull(json_unquote(json_extract(`StepJson`,_utf8mb4'$.TOverhaulNonSelf002.FAT')),ifnull(json_unquote(json_extract(`StepJson`,_utf8mb4'$.THWC010.FAT')),ifnull(json_unquote(json_extract(`StepJson`,_utf8mb4'$.THWC010_RE.FAT')),ifnull(json_unquote(json_extract(`StepJson`,_utf8mb4'$.TFinanceService001.FAT')),ifnull(json_unquote(json_extract(`StepJson`,_utf8mb4'$.TDismantleCode002.FAT')),ifnull(json_unquote(json_extract(`StepJson`,_utf8mb4'$.TDismantleCode006.FAT')),ifnull(json_unquote(json_extract(`StepJson`,_utf8mb4'$.TCW001_RE.FAT')),ifnull(json_unquote(json_extract(`StepJson`,_utf8mb4'$.TCW001.FAT')),ifnull(json_unquote(json_extract(`StepJson`,_utf8mb4'$.TOverhaulCode002.FAT')),ifnull(json_unquote(json_extract(`StepJson`,_utf8mb4'$.TOverhaulCode006.FAT')),ifnull(json_unquote(json_extract(`StepJson`,_utf8mb4'$.TCheckCar010_RE.FAT')),ifnull(json_unquote(json_extract(`StepJson`,_utf8mb4'$.TCheckCar010.FAT')),ifnull(json_unquote(json_extract(`StepJson`,_utf8mb4'$.TDismantleNonSelf001.FAT')),ifnull(json_unquote(json_extract(`StepJson`,_utf8mb4'$.TDismantleNonSelf002.FAT')),ifnull(json_unquote(json_extract(`StepJson`,_utf8mb4'$.TInstallNonSelf001.FAT')),ifnull(json_unquote(json_extract(`StepJson`,_utf8mb4'$.TInstallNonSelf002.FAT')),ifnull(json_unquote(json_extract(`StepJson`,_utf8mb4'$.TBeforeLoan001.FAT')),ifnull(json_unquote(json_extract(`StepJson`,_utf8mb4'$.TMultiple001_ReDistribute.FAT')),ifnull(json_unquote(json_extract(`StepJson`,_utf8mb4'$.TMultiple001_Distribute.FAT')),ifnull(json_unquote(json_extract(`StepJson`,_utf8mb4'$.TSwitchCode007.FAT')),ifnull(json_unquote(json_extract(`StepJson`,_utf8mb4'$.TSwitchCode002.FAT')),ifnull(json_unquote(json_extract(`StepJson`,_utf8mb4'$.TSwitchNonSelf001.FAT')),ifnull(json_unquote(json_extract(`StepJson`,_utf8mb4'$.TSwitchNonSelf002.FAT')),ifnull(json_unquote(json_extract(`StepJson`,_utf8mb4'$.TVehicleBus_01.FAT')),NULL)))))))))))))))))))))))))) VIRTUAL COMMENT '首次分派时间',
  `v_LastDistributeTime` datetime GENERATED ALWAYS AS (ifnull(json_unquote(json_extract(`StepJson`,_utf8mb4'$.TBeforeLoan001.LAT')),ifnull(json_unquote(json_extract(`StepJson`,_utf8mb4'$.TCheckCar010.LAT')),ifnull(json_unquote(json_extract(`StepJson`,_utf8mb4'$.TCheckCar010_RE.LAT')),ifnull(json_unquote(json_extract(`StepJson`,_utf8mb4'$.TChild002.LAT')),ifnull(json_unquote(json_extract(`StepJson`,_utf8mb4'$.TChild002_RE.LAT')),ifnull(json_unquote(json_extract(`StepJson`,_utf8mb4'$.TCW001.LAT')),ifnull(json_unquote(json_extract(`StepJson`,_utf8mb4'$.TCW001_RE.LAT')),ifnull(json_unquote(json_extract(`StepJson`,_utf8mb4'$.TDismantleCode002.LAT')),ifnull(json_unquote(json_extract(`StepJson`,_utf8mb4'$.TDismantleCode006.LAT')),ifnull(json_unquote(json_extract(`StepJson`,_utf8mb4'$.TDismantleNonSelf001.LAT')),ifnull(json_unquote(json_extract(`StepJson`,_utf8mb4'$.TDismantleNonSelf002.LAT')),ifnull(json_unquote(json_extract(`StepJson`,_utf8mb4'$.TETC004.LAT')),ifnull(json_unquote(json_extract(`StepJson`,_utf8mb4'$.TFinanceService001.LAT')),ifnull(json_unquote(json_extract(`StepJson`,_utf8mb4'$.THWC010.LAT')),ifnull(json_unquote(json_extract(`StepJson`,_utf8mb4'$.THWC010_RE.LAT')),ifnull(json_unquote(json_extract(`StepJson`,_utf8mb4'$.TInstallNonSelf001.LAT')),ifnull(json_unquote(json_extract(`StepJson`,_utf8mb4'$.TInstallNonSelf002.LAT')),ifnull(json_unquote(json_extract(`StepJson`,_utf8mb4'$.TMultiple001_Distribute.LAT')),ifnull(json_unquote(json_extract(`StepJson`,_utf8mb4'$.TMultiple001_ReDistribute.LAT')),ifnull(json_unquote(json_extract(`StepJson`,_utf8mb4'$.TOverhaulCode002.LAT')),ifnull(json_unquote(json_extract(`StepJson`,_utf8mb4'$.TOverhaulCode006.LAT')),ifnull(json_unquote(json_extract(`StepJson`,_utf8mb4'$.TOverhaulNonSelf001.LAT')),ifnull(json_unquote(json_extract(`StepJson`,_utf8mb4'$.TOverhaulNonSelf002.LAT')),ifnull(json_unquote(json_extract(`StepJson`,_utf8mb4'$.TSwitchCode002.LAT')),ifnull(json_unquote(json_extract(`StepJson`,_utf8mb4'$.TSwitchCode007.LAT')),ifnull(json_unquote(json_extract(`StepJson`,_utf8mb4'$.TSwitchNonSelf001.LAT')),ifnull(json_unquote(json_extract(`StepJson`,_utf8mb4'$.TSwitchNonSelf002.LAT')),ifnull(json_unquote(json_extract(`StepJson`,_utf8mb4'$.TVehicleBus_01.LAT')),ifnull(json_unquote(json_extract(`StepJson`,_utf8mb4'$.TVehicleBus_04.LAT')),NULL)))))))))))))))))))))))))))))) VIRTUAL COMMENT '最新分派时间',
  `v_FirstDispatcherCode` varchar(50) GENERATED ALWAYS AS (ifnull(json_unquote(json_extract(`StepJson`,_utf8mb4'$.POverhaulNonSelf001.FAP')),ifnull(json_unquote(json_extract(`StepJson`,_utf8mb4'$.POverhaulNonSelf002.FAP')),ifnull(json_unquote(json_extract(`StepJson`,_utf8mb4'$.PHWC010.FAP')),ifnull(json_unquote(json_extract(`StepJson`,_utf8mb4'$.PHWC010_RE.FAP')),ifnull(json_unquote(json_extract(`StepJson`,_utf8mb4'$.PFinanceService001.FAP')),ifnull(json_unquote(json_extract(`StepJson`,_utf8mb4'$.PDismantleCode002.FAP')),ifnull(json_unquote(json_extract(`StepJson`,_utf8mb4'$.PDismantleCode006.FAP')),ifnull(json_unquote(json_extract(`StepJson`,_utf8mb4'$.PCW001_RE.FAP')),ifnull(json_unquote(json_extract(`StepJson`,_utf8mb4'$.PCW001.FAP')),ifnull(json_unquote(json_extract(`StepJson`,_utf8mb4'$.POverhaulCode002.FAP')),ifnull(json_unquote(json_extract(`StepJson`,_utf8mb4'$.POverhaulCode006.FAP')),ifnull(json_unquote(json_extract(`StepJson`,_utf8mb4'$.PCheckCar010_RE.FAP')),ifnull(json_unquote(json_extract(`StepJson`,_utf8mb4'$.PCheckCar010.FAP')),ifnull(json_unquote(json_extract(`StepJson`,_utf8mb4'$.PDismantleNonSelf001.FAP')),ifnull(json_unquote(json_extract(`StepJson`,_utf8mb4'$.PDismantleNonSelf002.FAP')),ifnull(json_unquote(json_extract(`StepJson`,_utf8mb4'$.PInstallNonSelf001.FAP')),ifnull(json_unquote(json_extract(`StepJson`,_utf8mb4'$.PInstallNonSelf002.FAP')),ifnull(json_unquote(json_extract(`StepJson`,_utf8mb4'$.PBeforeLoan001.FAP')),ifnull(json_unquote(json_extract(`StepJson`,_utf8mb4'$.PMultiple001_ReDistribute.FAP')),ifnull(json_unquote(json_extract(`StepJson`,_utf8mb4'$.PMultiple001_Distribute.FAP')),ifnull(json_unquote(json_extract(`StepJson`,_utf8mb4'$.PSwitchCode007.FAP')),ifnull(json_unquote(json_extract(`StepJson`,_utf8mb4'$.PSwitchCode002.FAP')),ifnull(json_unquote(json_extract(`StepJson`,_utf8mb4'$.PSwitchNonSelf001.FAP')),ifnull(json_unquote(json_extract(`StepJson`,_utf8mb4'$.PSwitchNonSelf002.FAP')),ifnull(json_unquote(json_extract(`StepJson`,_utf8mb4'$.PVehicleBus_01.FAP')),NULL)))))))))))))))))))))))))) VIRTUAL COMMENT '首次分派人Code',
  `v_FirstDispatcherName` varchar(100) GENERATED ALWAYS AS (ifnull(json_unquote(json_extract(`StepJson`,_utf8mb4'$.NOverhaulNonSelf001.FAN')),ifnull(json_unquote(json_extract(`StepJson`,_utf8mb4'$.NOverhaulNonSelf002.FAN')),ifnull(json_unquote(json_extract(`StepJson`,_utf8mb4'$.NHWC010.FAN')),ifnull(json_unquote(json_extract(`StepJson`,_utf8mb4'$.NHWC010_RE.FAN')),ifnull(json_unquote(json_extract(`StepJson`,_utf8mb4'$.NFinanceService001.FAN')),ifnull(json_unquote(json_extract(`StepJson`,_utf8mb4'$.NDismantleCode002.FAN')),ifnull(json_unquote(json_extract(`StepJson`,_utf8mb4'$.NDismantleCode006.FAN')),ifnull(json_unquote(json_extract(`StepJson`,_utf8mb4'$.NCW001_RE.FAN')),ifnull(json_unquote(json_extract(`StepJson`,_utf8mb4'$.NCW001.FAN')),ifnull(json_unquote(json_extract(`StepJson`,_utf8mb4'$.NOverhaulCode002.FAN')),ifnull(json_unquote(json_extract(`StepJson`,_utf8mb4'$.NOverhaulCode006.FAN')),ifnull(json_unquote(json_extract(`StepJson`,_utf8mb4'$.NCheckCar010_RE.FAN')),ifnull(json_unquote(json_extract(`StepJson`,_utf8mb4'$.NCheckCar010.FAN')),ifnull(json_unquote(json_extract(`StepJson`,_utf8mb4'$.NDismantleNonSelf001.FAN')),ifnull(json_unquote(json_extract(`StepJson`,_utf8mb4'$.NDismantleNonSelf002.FAN')),ifnull(json_unquote(json_extract(`StepJson`,_utf8mb4'$.NInstallNonSelf001.FAN')),ifnull(json_unquote(json_extract(`StepJson`,_utf8mb4'$.NInstallNonSelf002.FAN')),ifnull(json_unquote(json_extract(`StepJson`,_utf8mb4'$.NBeforeLoan001.FAN')),ifnull(json_unquote(json_extract(`StepJson`,_utf8mb4'$.NMultiple001_ReDistribute.FAN')),ifnull(json_unquote(json_extract(`StepJson`,_utf8mb4'$.NMultiple001_Distribute.FAN')),ifnull(json_unquote(json_extract(`StepJson`,_utf8mb4'$.NSwitchCode007.FAN')),ifnull(json_unquote(json_extract(`StepJson`,_utf8mb4'$.NSwitchCode002.FAN')),ifnull(json_unquote(json_extract(`StepJson`,_utf8mb4'$.NSwitchNonSelf001.FAN')),ifnull(json_unquote(json_extract(`StepJson`,_utf8mb4'$.NSwitchNonSelf002.FAN')),ifnull(json_unquote(json_extract(`StepJson`,_utf8mb4'$.NVehicleBus_01.FAN')),NULL)))))))))))))))))))))))))) VIRTUAL COMMENT '首次分派人名字',
  `v_LastDispatcherCode` varchar(50) GENERATED ALWAYS AS (ifnull(json_unquote(json_extract(`StepJson`,_utf8mb4'$.POverhaulNonSelf001.LAP')),ifnull(json_unquote(json_extract(`StepJson`,_utf8mb4'$.POverhaulNonSelf002.LAP')),ifnull(json_unquote(json_extract(`StepJson`,_utf8mb4'$.PCarHornbill002.LAP')),ifnull(json_unquote(json_extract(`StepJson`,_utf8mb4'$.PHWC010.LAP')),ifnull(json_unquote(json_extract(`StepJson`,_utf8mb4'$.PHWC010_RE.LAP')),ifnull(json_unquote(json_extract(`StepJson`,_utf8mb4'$.PFinanceService001.LAP')),ifnull(json_unquote(json_extract(`StepJson`,_utf8mb4'$.PDismantleCode002.LAP')),ifnull(json_unquote(json_extract(`StepJson`,_utf8mb4'$.PDismantleCode006.LAP')),ifnull(json_unquote(json_extract(`StepJson`,_utf8mb4'$.PCW001_RE.LAP')),ifnull(json_unquote(json_extract(`StepJson`,_utf8mb4'$.PCW001.LAP')),ifnull(json_unquote(json_extract(`StepJson`,_utf8mb4'$.POverhaulCode002.LAP')),ifnull(json_unquote(json_extract(`StepJson`,_utf8mb4'$.POverhaulCode006.LAP')),ifnull(json_unquote(json_extract(`StepJson`,_utf8mb4'$.PCheckCar010_RE.LAP')),ifnull(json_unquote(json_extract(`StepJson`,_utf8mb4'$.PCheckCar010.LAP')),ifnull(json_unquote(json_extract(`StepJson`,_utf8mb4'$.PDismantleNonSelf001.LAP')),ifnull(json_unquote(json_extract(`StepJson`,_utf8mb4'$.PDismantleNonSelf002.LAP')),ifnull(json_unquote(json_extract(`StepJson`,_utf8mb4'$.PInstallNonSelf001.LAP')),ifnull(json_unquote(json_extract(`StepJson`,_utf8mb4'$.PInstallNonSelf002.LAP')),ifnull(json_unquote(json_extract(`StepJson`,_utf8mb4'$.PBeforeLoan001.LAP')),ifnull(json_unquote(json_extract(`StepJson`,_utf8mb4'$.PMultiple001_ReDistribute.LAP')),ifnull(json_unquote(json_extract(`StepJson`,_utf8mb4'$.PMultiple001_Distribute.LAP')),ifnull(json_unquote(json_extract(`StepJson`,_utf8mb4'$.PSwitchCode007.LAP')),ifnull(json_unquote(json_extract(`StepJson`,_utf8mb4'$.PSwitchCode002.LAP')),ifnull(json_unquote(json_extract(`StepJson`,_utf8mb4'$.PSwitchNonSelf001.LAP')),ifnull(json_unquote(json_extract(`StepJson`,_utf8mb4'$.PSwitchNonSelf002.LAP')),ifnull(json_unquote(json_extract(`StepJson`,_utf8mb4'$.PVehicleBus_01.LAP')),NULL))))))))))))))))))))))))))) VIRTUAL COMMENT '最后一次分派人Code',
  `v_LastDispatcherName` varchar(100) GENERATED ALWAYS AS (ifnull(json_unquote(json_extract(`StepJson`,_utf8mb4'$.NOverhaulNonSelf001.LAN')),ifnull(json_unquote(json_extract(`StepJson`,_utf8mb4'$.NOverhaulNonSelf002.LAN')),ifnull(json_unquote(json_extract(`StepJson`,_utf8mb4'$.NCarHornbill002.LAN')),ifnull(json_unquote(json_extract(`StepJson`,_utf8mb4'$.NHWC010.LAN')),ifnull(json_unquote(json_extract(`StepJson`,_utf8mb4'$.NHWC010_RE.LAN')),ifnull(json_unquote(json_extract(`StepJson`,_utf8mb4'$.NFinanceService001.LAN')),ifnull(json_unquote(json_extract(`StepJson`,_utf8mb4'$.NDismantleCode002.LAN')),ifnull(json_unquote(json_extract(`StepJson`,_utf8mb4'$.NDismantleCode006.LAN')),ifnull(json_unquote(json_extract(`StepJson`,_utf8mb4'$.NCW001_RE.LAN')),ifnull(json_unquote(json_extract(`StepJson`,_utf8mb4'$.NCW001.LAN')),ifnull(json_unquote(json_extract(`StepJson`,_utf8mb4'$.NOverhaulCode002.LAN')),ifnull(json_unquote(json_extract(`StepJson`,_utf8mb4'$.NOverhaulCode006.LAN')),ifnull(json_unquote(json_extract(`StepJson`,_utf8mb4'$.NCheckCar010_RE.LAN')),ifnull(json_unquote(json_extract(`StepJson`,_utf8mb4'$.NCheckCar010.LAN')),ifnull(json_unquote(json_extract(`StepJson`,_utf8mb4'$.NDismantleNonSelf001.LAN')),ifnull(json_unquote(json_extract(`StepJson`,_utf8mb4'$.NDismantleNonSelf002.LAN')),ifnull(json_unquote(json_extract(`StepJson`,_utf8mb4'$.NInstallNonSelf001.LAN')),ifnull(json_unquote(json_extract(`StepJson`,_utf8mb4'$.NInstallNonSelf002.LAN')),ifnull(json_unquote(json_extract(`StepJson`,_utf8mb4'$.NBeforeLoan001.LAN')),ifnull(json_unquote(json_extract(`StepJson`,_utf8mb4'$.NMultiple001_ReDistribute.LAN')),ifnull(json_unquote(json_extract(`StepJson`,_utf8mb4'$.NMultiple001_Distribute.LAN')),ifnull(json_unquote(json_extract(`StepJson`,_utf8mb4'$.NSwitchCode007.LAN')),ifnull(json_unquote(json_extract(`StepJson`,_utf8mb4'$.NSwitchCode002.LAN')),ifnull(json_unquote(json_extract(`StepJson`,_utf8mb4'$.NSwitchNonSelf001.LAN')),ifnull(json_unquote(json_extract(`StepJson`,_utf8mb4'$.NSwitchNonSelf002.LAN')),ifnull(json_unquote(json_extract(`StepJson`,_utf8mb4'$.NVehicleBus_01.LAN')),ifnull(json_unquote(json_extract(`StepJson`,_utf8mb4'$."NSwitch-VehicleBus_04".LAN')),NULL)))))))))))))))))))))))))))) VIRTUAL COMMENT '最后一次分派人名字',
  `v_StartTime` datetime GENERATED ALWAYS AS (ifnull(json_unquote(json_extract(`StepJson`,_utf8mb4'$.TCarHornbill004.LAT')),NULL)) VIRTUAL,
  `v_ArrivalTime` datetime GENERATED ALWAYS AS (ifnull(json_unquote(json_extract(`StepJson`,_utf8mb4'$.TCarHornbill005.LAT')),NULL)) VIRTUAL,
  `v_LastAcceptTime` datetime GENERATED ALWAYS AS (ifnull(json_unquote(json_extract(`StepJson`,_utf8mb4'$.TCarHornbill003.LAT')),NULL)) VIRTUAL,
  `v_LastAcceptCode` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci GENERATED ALWAYS AS (ifnull(json_unquote(json_extract(`StepJson`,_utf8mb4'$.PCarHornbill003.LAP')),NULL)) VIRTUAL,
  `v_LastAcceptName` varchar(100) CHARACTER SET utf8 COLLATE utf8_general_ci GENERATED ALWAYS AS (ifnull(json_unquote(json_extract(`StepJson`,_utf8mb4'$.NCarHornbill003.LAN')),NULL)) VIRTUAL,
  `v_LastRecordPersonCode` varchar(100) GENERATED ALWAYS AS (ifnull(json_unquote(json_extract(`StepJson`,_utf8mb4'$.PBeforeLoan008.LAP')),ifnull(json_unquote(json_extract(`StepJson`,_utf8mb4'$.PCarHornbill006.LAP')),ifnull(json_unquote(json_extract(`StepJson`,_utf8mb4'$.PCheckCar030.LAP')),ifnull(json_unquote(json_extract(`StepJson`,_utf8mb4'$.PChild004.LAP')),ifnull(json_unquote(json_extract(`StepJson`,_utf8mb4'$.PChild004_Re.LAP')),ifnull(json_unquote(json_extract(`StepJson`,_utf8mb4'$.PCode1004001002.LAP')),ifnull(json_unquote(json_extract(`StepJson`,_utf8mb4'$.PCode1004002002.LAP')),ifnull(json_unquote(json_extract(`StepJson`,_utf8mb4'$.PCode1004003002.LAP')),ifnull(json_unquote(json_extract(`StepJson`,_utf8mb4'$.PCode1004004005.LAP')),ifnull(json_unquote(json_extract(`StepJson`,_utf8mb4'$.PCode1004005005.LAP')),ifnull(json_unquote(json_extract(`StepJson`,_utf8mb4'$.PCW004.LAP')),ifnull(json_unquote(json_extract(`StepJson`,_utf8mb4'$.PDismantleCode004.LAP')),ifnull(json_unquote(json_extract(`StepJson`,_utf8mb4'$.PDismantleCode007.LAP')),ifnull(json_unquote(json_extract(`StepJson`,_utf8mb4'$.PDismantleCode008.LAP')),ifnull(json_unquote(json_extract(`StepJson`,_utf8mb4'$.PDismantleNonSelf003.LAP')),ifnull(json_unquote(json_extract(`StepJson`,_utf8mb4'$.PDismantleNonSelf007.LAP')),ifnull(json_unquote(json_extract(`StepJson`,_utf8mb4'$.PETC001.LAP')),ifnull(json_unquote(json_extract(`StepJson`,_utf8mb4'$.PFinanceService007.LAP')),ifnull(json_unquote(json_extract(`StepJson`,_utf8mb4'$.PHWC030.LAP')),ifnull(json_unquote(json_extract(`StepJson`,_utf8mb4'$.PHWC030_RE.LAP')),ifnull(json_unquote(json_extract(`StepJson`,_utf8mb4'$.PInstallNonSelf003.LAP')),ifnull(json_unquote(json_extract(`StepJson`,_utf8mb4'$.PInstallNonSelf007.LAP')),ifnull(json_unquote(json_extract(`StepJson`,_utf8mb4'$.PMultiple001_DecCustAudit.LAP')),ifnull(json_unquote(json_extract(`StepJson`,_utf8mb4'$.PMultiple001_Record.LAP')),ifnull(json_unquote(json_extract(`StepJson`,_utf8mb4'$.POverhaulCode004.LAP')),ifnull(json_unquote(json_extract(`StepJson`,_utf8mb4'$.POverhaulCode007.LAP')),ifnull(json_unquote(json_extract(`StepJson`,_utf8mb4'$.POverhaulCode008.LAP')),ifnull(json_unquote(json_extract(`StepJson`,_utf8mb4'$.POverhaulNonSelf003.LAP')),ifnull(json_unquote(json_extract(`StepJson`,_utf8mb4'$.POverhaulNonSelf007.LAP')),ifnull(json_unquote(json_extract(`StepJson`,_utf8mb4'$.PSwitchCode004.LAP')),ifnull(json_unquote(json_extract(`StepJson`,_utf8mb4'$.PSwitchCode006.LAP')),ifnull(json_unquote(json_extract(`StepJson`,_utf8mb4'$.PSwitchCode008.LAP')),ifnull(json_unquote(json_extract(`StepJson`,_utf8mb4'$.PSwitchNonSelf003.LAP')),ifnull(json_unquote(json_extract(`StepJson`,_utf8mb4'$.PSwitchNonSelf007.LAP')),ifnull(json_unquote(json_extract(`StepJson`,_utf8mb4'$.PVehicleBus_03.LAP')),ifnull(json_unquote(json_extract(`StepJson`,_utf8mb4'$.PZcpCode002.LAP')),ifnull(json_unquote(json_extract(`StepJson`,_utf8mb4'$.PZcpCode003_RE.LAP')),NULL)))))))))))))))))))))))))))))))))))))) VIRTUAL COMMENT '最新备案人Code',
  `v_LastRecordPersonName` varchar(100) GENERATED ALWAYS AS (ifnull(json_unquote(json_extract(`StepJson`,_utf8mb4'$.NBeforeLoan008.LAN')),ifnull(json_unquote(json_extract(`StepJson`,_utf8mb4'$.NCW004.LAN')),ifnull(json_unquote(json_extract(`StepJson`,_utf8mb4'$.NCarHornbill006.LAN')),ifnull(json_unquote(json_extract(`StepJson`,_utf8mb4'$.NCheckCar030.LAN')),ifnull(json_unquote(json_extract(`StepJson`,_utf8mb4'$.NChild004.LAN')),ifnull(json_unquote(json_extract(`StepJson`,_utf8mb4'$.NChild004_Re.LAN')),ifnull(json_unquote(json_extract(`StepJson`,_utf8mb4'$.NCode1004001002.LAN')),ifnull(json_unquote(json_extract(`StepJson`,_utf8mb4'$.NCode1004002002.LAN')),ifnull(json_unquote(json_extract(`StepJson`,_utf8mb4'$.NCode1004003002.LAN')),ifnull(json_unquote(json_extract(`StepJson`,_utf8mb4'$.NCode1004004005.LAN')),ifnull(json_unquote(json_extract(`StepJson`,_utf8mb4'$.NCode1004005005.LAN')),ifnull(json_unquote(json_extract(`StepJson`,_utf8mb4'$.NDismantleCode004.LAN')),ifnull(json_unquote(json_extract(`StepJson`,_utf8mb4'$.NDismantleCode007.LAN')),ifnull(json_unquote(json_extract(`StepJson`,_utf8mb4'$.NDismantleCode008.LAN')),ifnull(json_unquote(json_extract(`StepJson`,_utf8mb4'$.NDismantleNonSelf003.LAN')),ifnull(json_unquote(json_extract(`StepJson`,_utf8mb4'$.NDismantleNonSelf007.LAN')),ifnull(json_unquote(json_extract(`StepJson`,_utf8mb4'$.NETC001.LAN')),ifnull(json_unquote(json_extract(`StepJson`,_utf8mb4'$.NFinanceService007.LAN')),ifnull(json_unquote(json_extract(`StepJson`,_utf8mb4'$.NHWC030.LAN')),ifnull(json_unquote(json_extract(`StepJson`,_utf8mb4'$.NHWC030_RE.LAN')),ifnull(json_unquote(json_extract(`StepJson`,_utf8mb4'$.NInstallNonSelf003.LAN')),ifnull(json_unquote(json_extract(`StepJson`,_utf8mb4'$.NInstallNonSelf007.LAN')),ifnull(json_unquote(json_extract(`StepJson`,_utf8mb4'$.NMultiple001_DecCustAudit.LAN')),ifnull(json_unquote(json_extract(`StepJson`,_utf8mb4'$.NMultiple001_Record.LAN')),ifnull(json_unquote(json_extract(`StepJson`,_utf8mb4'$.NOverhaulCode004.LAN')),ifnull(json_unquote(json_extract(`StepJson`,_utf8mb4'$.NOverhaulCode007.LAN')),ifnull(json_unquote(json_extract(`StepJson`,_utf8mb4'$.NOverhaulCode008.LAN')),ifnull(json_unquote(json_extract(`StepJson`,_utf8mb4'$.NOverhaulNonSelf003.LAN')),ifnull(json_unquote(json_extract(`StepJson`,_utf8mb4'$.NOverhaulNonSelf007.LAN')),ifnull(json_unquote(json_extract(`StepJson`,_utf8mb4'$.NSwitchCode004.LAN')),ifnull(json_unquote(json_extract(`StepJson`,_utf8mb4'$.NSwitchCode006.LAN')),ifnull(json_unquote(json_extract(`StepJson`,_utf8mb4'$.NSwitchCode008.LAN')),ifnull(json_unquote(json_extract(`StepJson`,_utf8mb4'$.NSwitchNonSelf003.LAN')),ifnull(json_unquote(json_extract(`StepJson`,_utf8mb4'$.NSwitchNonSelf007.LAN')),ifnull(json_unquote(json_extract(`StepJson`,_utf8mb4'$.NVehicleBus_03.LAN')),ifnull(json_unquote(json_extract(`StepJson`,_utf8mb4'$.NZcpCode002.LAN')),ifnull(json_unquote(json_extract(`StepJson`,_utf8mb4'$.NZcpCode003_RE.LAN')),NULL)))))))))))))))))))))))))))))))))))))) VIRTUAL COMMENT '最新备案人Name',
  `v_LastAddRecordTime` datetime GENERATED ALWAYS AS (ifnull(json_unquote(json_extract(`StepJson`,_utf8mb4'$.TCW007.LAT')),NULL)) VIRTUAL COMMENT '最后一次补录时间（VHS）',
  PRIMARY KEY (`Id`),
  KEY `1` (`WorkOrderId`),
  KEY `NON-RuntimeItemId` (`RuntimeItemId`),
  KEY `NON_ArrivalTime` (`v_ArrivalTime`),
  KEY `NON_LastAcceptCode` (`v_LastAcceptCode`),
  KEY `NON_LastAcceptName` (`v_LastAcceptName`),
  KEY `NON_LastAcceptTime` (`v_LastAcceptTime`),
  KEY `NON_LastDispatcherCode` (`v_LastDispatcherCode`),
  KEY `NON_LastDispatcherName` (`v_LastDispatcherName`),
  KEY `NON_LastDistributeTime` (`v_LastDistributeTime`),
  KEY `NON_LastRecordTime` (`v_LastRecordTime`),
  KEY `NON_OrderCompleteTime` (`v_OrderCompleteTime`),
  KEY `NON_StartTime` (`v_StartTime`),
  KEY `v_FirstAssignTime` (`v_FirstAssignTime`),
  KEY `v_FirstAuditPersonCode` (`v_FirstAuditPersonCode`),
  KEY `v_FirstAuditPersonName` (`v_FirstAuditPersonName`),
  KEY `v_FirstAuditTime` (`v_FirstAuditTime`),
  KEY `v_FirstCustAuditPersonCode` (`v_FirstCustAuditPersonCode`),
  KEY `v_FirstCustAuditPersonName` (`v_FirstCustAuditPersonName`),
  KEY `v_FirstCustAuditTime` (`v_FirstCustAuditTime`),
  KEY `v_FirstDispatcherCode` (`v_FirstDispatcherCode`),
  KEY `v_FirstDispatcherName` (`v_FirstDispatcherName`),
  KEY `v_FirstDistributeTime` (`v_FirstDistributeTime`),
  KEY `v_FirstRecordPersonCode` (`v_FirstRecordPersonCode`),
  KEY `v_FirstRecordPersonName` (`v_FirstRecordPersonName`),
  KEY `v_FirstRecordTime` (`v_FirstRecordTime`),
  KEY `v_LastAuditPersonCode` (`v_LastAuditPersonCode`),
  KEY `v_LastAuditPersonName` (`v_LastAuditPersonName`),
  KEY `v_LastAuditTime` (`v_LastAuditTime`),
  KEY `v_LastCustAuditPersonCode` (`v_LastCustAuditPersonCode`),
  KEY `v_LastCustAuditPersonName` (`v_LastCustAuditPersonName`),
  KEY `v_LastCustAuditTime` (`v_LastCustAuditTime`),
  KEY `v_LastDispatcherCode` (`v_LastDispatcherCode`),
  KEY `v_LastDispatcherName` (`v_LastDispatcherName`),
  KEY `v_LastDistributeTime` (`v_LastDistributeTime`),
  KEY `v_LastRecordTime` (`v_LastRecordTime`),
  KEY `v_OrderCompleteTime` (`v_OrderCompleteTime`),
  KEY `NON-LastRecordPersonName` (`v_LastRecordPersonName`),
  KEY `NON-LastRecordPersonCode` (`v_LastRecordPersonCode`),
  KEY `NON-v_LastAddRecordTime` (`v_LastAddRecordTime`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 ROW_FORMAT=DYNAMIC
;

INSERT INTO serviceordercenterhistest.tb_workflowjsoninfo(Id,WorkOrderId,RuntimeItemId,StepJson,SourceMode,InsertTime,Deleted)
SELECT Id,WorkOrderId,RuntimeItemId,StepJson,SourceMode,InsertTime,Deleted
FROM serviceordercenter.tb_workflowjsoninfo;

INSERT INTO serviceordercenterhistest.tb_workgoodsinfo(`Id`, `WorkOrderId`, `MallOrderId`, `OrderNo`, `GoodsSource`, `BrandId`, `BrandCode`, `BrandName`, `GoodsId`, `GoodsName`, `GoodsType`, `GoodsPriceId`, `SaleName`, `GoodsAmount`, `CoopProductId`, `CoopProductName`, `GoodsPrice`, `MallOrderIdHis`, `OrderTypeHis`, `CarIdHis`, `Seller`, `ExtraJson`, `InstallResult`, `InstallFailReason`, `CreatedById`, `CreatedAt`, `UpdatedById`, `UpdatedAt`, `DeletedById`, `DeletedAt`, `Deleted`, `LastUpdateTimeStamp`
)
SELECT `Id`, `WorkOrderId`, `MallOrderId`, `OrderNo`, `GoodsSource`, `BrandId`, `BrandCode`, `BrandName`, `GoodsId`, `GoodsName`, `GoodsType`, `GoodsPriceId`, `SaleName`, `GoodsAmount`, `CoopProductId`, `CoopProductName`, `GoodsPrice`, `MallOrderIdHis`, `OrderTypeHis`, `CarIdHis`, `Seller`, `ExtraJson`, `InstallResult`, `InstallFailReason`, `CreatedById`, `CreatedAt`, `UpdatedById`, `UpdatedAt`, `DeletedById`, `DeletedAt`, `Deleted`, `LastUpdateTimeStamp`
FROM serviceordercenter.tb_workgoodsinfo;

DROP TABLE IF EXISTS serviceordercenterhistest.tb_worksurveydetail;
CREATE TABLE serviceordercenterhistest.`tb_worksurveydetail` (
  `Id` char(12) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL COMMENT '主键(CK)',
  `WorkOrderId` char(12) DEFAULT NULL COMMENT '工单Id',
  `DeviceVirtualCode` varchar(500) DEFAULT NULL COMMENT '设备虚拟编码',
  `DeviceNumber` varchar(500) DEFAULT NULL COMMENT '设备唯一编码',
  `IsExistDeviceUnique` smallint(6) DEFAULT NULL COMMENT '是否存在设备唯一编码：0.不存在；1.存在；',
  `TempAssetName` text COMMENT '资产名称',
  `TempAssetBrand` varchar(100) DEFAULT NULL COMMENT '资产品牌',
  `TempAssetModel` text COMMENT '资产型号',
  `TempAssetNumber` varchar(50) DEFAULT NULL COMMENT '资产编号',
  `TempAssetPlate` varchar(100) DEFAULT NULL COMMENT '资产铭牌',
  `TempAssetType` smallint(6) DEFAULT NULL COMMENT '资产类型：1.光学机械；2.包装机械；3.木工机械；4.印染机械；5.纺织机械；6.印刷机械；7.金属切削；8.塑胶成型；9.辅助设备；',
  `IsUnusual` smallint(6) DEFAULT NULL COMMENT '是否异常：0.否；1.是；',
  `UnusualType` varchar(50) DEFAULT NULL COMMENT '异常类别',
  `UnusualRemark` varchar(100) DEFAULT NULL COMMENT '异常备注',
  `WorkGoodsId` char(12) DEFAULT NULL COMMENT '工单商品Id',
  `IsInstallGPS` smallint(6) DEFAULT NULL COMMENT '是否加装GPS：0.否；1.是；',
  `InstallOrderId` char(12) DEFAULT NULL COMMENT 'GPS加装工单Id',
  `RecordStatus` smallint(6) DEFAULT NULL COMMENT '录入状态：0.待录入；1.录入完成；',
  `CheckStatus` smallint(6) DEFAULT NULL COMMENT '审核状态：0.不合格；1.合格；',
  `FailReason` varchar(200) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL COMMENT '不合格原因',
  `CreatedAt` datetime DEFAULT NULL,
  `CreatedById` char(36) DEFAULT NULL,
  `UpdatedAt` datetime DEFAULT NULL,
  `UpdatedById` char(36) DEFAULT NULL,
  `DeletedAt` datetime DEFAULT NULL,
  `DeletedById` char(36) DEFAULT NULL,
  `Deleted` smallint(6) DEFAULT NULL,
  PRIMARY KEY (`Id`),
  KEY `NON-WorkOrderId` (`WorkOrderId`) USING BTREE,
  KEY `NON-DeviceVirtualCode` (`DeviceVirtualCode`) USING BTREE,
  KEY `NON-WorkGoodsId` (`WorkGoodsId`) USING BTREE,
  KEY `NON-InstallOrderId` (`InstallOrderId`) USING BTREE,
  KEY `NON-DeviceNumber` (`DeviceNumber`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='工单查勘工单明细'
;

INSERT INTO serviceordercenterhistest.tb_worksurveydetail
SELECT *
FROM serviceordercenter.tb_worksurveydetail;

DROP TABLE IF EXISTS serviceordercenterhistest.tb_workbussinessjsoninfo;
CREATE TABLE serviceordercenterhistest.`tb_workbussinessjsoninfo` (
  `Id` int(11) NOT NULL AUTO_INCREMENT COMMENT '自增主键',
  `WorkOrderId` char(12) DEFAULT NULL COMMENT '工单主单主键(tb_workorderinfo.Id)',
  `BussinessJson` json DEFAULT NULL COMMENT '处理人信息JSON',
  `InsertTime` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `Deleted` tinyint(1) NOT NULL DEFAULT '0',
  `appointTime` date GENERATED ALWAYS AS (json_unquote(json_extract(`BussinessJson`,_utf8mb4'$.appointTime'))) VIRTUAL COMMENT '(AFC)预计上门时间',
  `AppraisalStatus` int(11) GENERATED ALWAYS AS (json_unquote(json_extract(`BussinessJson`,_utf8mb4'$.AppraisalStatus'))) VIRTUAL COMMENT '(VHS)考核状态(0质量考核中 1质量考核通过 2质量考核驳回)',
  `v_LastNegotiatorTime` datetime GENERATED ALWAYS AS (ifnull(json_unquote(json_extract(`BussinessJson`,_utf8mb4'$.LastNegotiatorTime')),json_unquote(json_extract(`BussinessJson`,_utf8mb4'$.NegotiatorTime')))) VIRTUAL COMMENT '(AFC)最后一次提交谈判记录时间',
  `v_ReturnedTypeCode` varchar(20) GENERATED ALWAYS AS (json_unquote(json_extract(`BussinessJson`,_utf8mb4'$.ReturnedTypeCode'))) VIRTUAL COMMENT '(AFC)还款状态Code（basic_datadictionary.Code)',
  `v_IfRemove` smallint(6) GENERATED ALWAYS AS (json_unquote(json_extract(`BussinessJson`,_utf8mb4'$.IfRemove'))) VIRTUAL COMMENT '(AFC)是否移除（int 0否，1是）',
  `v_FollowFrequency` varchar(12) GENERATED ALWAYS AS (json_unquote(json_extract(`BussinessJson`,_utf8mb4'$.FollowFrequency'))) VIRTUAL COMMENT '(AFC)跟进频次(1 高频跟进,2 低频跟进)',
  `v_FollowFrequencyType` smallint(6) GENERATED ALWAYS AS (json_unquote(json_extract(`BussinessJson`,_utf8mb4'$.FollowFrequencyType'))) VIRTUAL COMMENT '(AFC)跟进频次类型（null&0访后，1访前）',
  `v_AfcCompleteType` smallint(6) GENERATED ALWAYS AS (json_unquote(json_extract(`BussinessJson`,_utf8mb4'$.AfcCompleteType'))) VIRTUAL COMMENT '(AFC)完成类型（0&null否，1手动结束，2正常结束，3超时自动结束）',
  `v_ReportDeadline` datetime GENERATED ALWAYS AS (json_unquote(json_extract(`BussinessJson`,_utf8mb4'$.reportDeadline'))) VIRTUAL COMMENT '(AFC)报告截止时间',
  `v_UnFollowDays` bigint(20) GENERATED ALWAYS AS (json_unquote(json_extract(`BussinessJson`,_utf8mb4'$.UnFollowDays'))) VIRTUAL COMMENT '(AFC)未跟进天数(当前时间-最新谈判记录提交时间-1，若值为-1则置0，超出退案时间不更新）',
  `v_IsRelateEtc` smallint(6) GENERATED ALWAYS AS (json_unquote(json_extract(`BussinessJson`,_utf8mb4'$.IsRelateEtc'))) VIRTUAL COMMENT '(VHS)是否关联ETC工单（1是0否）',
  `v_IfEtcRecord` smallint(6) GENERATED ALWAYS AS (json_unquote(json_extract(`BussinessJson`,_utf8mb4'$.IfEtcRecord'))) VIRTUAL COMMENT '(VHS)关联ETC工单是否备案（1是0否）',
  `v_RescuerName` varchar(50) GENERATED ALWAYS AS (json_unquote(json_extract(`BussinessJson`,_utf8mb4'$.RescuerName'))) VIRTUAL COMMENT '(CHB)救援人姓名',
  `v_RescuerTel` varchar(20) GENERATED ALWAYS AS (json_unquote(json_extract(`BussinessJson`,_utf8mb4'$.RescuerTel'))) VIRTUAL COMMENT '(CHB)救援人电话',
  `v_RescuerPlateNumber` varchar(50) GENERATED ALWAYS AS (json_unquote(json_extract(`BussinessJson`,_utf8mb4'$.RescuerPlateNumber'))) VIRTUAL COMMENT '(CHB)救援人车牌号',
  `v_RelateWorkOrderId` varchar(20) GENERATED ALWAYS AS (json_unquote(json_extract(`BussinessJson`,_utf8mb4'$.RelateWorkOrderId'))) VIRTUAL COMMENT '(CHB)关联工单Id',
  `DynamicId` varchar(20) NOT NULL DEFAULT 'FA-' COMMENT '动态表单Id',
  `v_DynIsHelpers` varchar(20) GENERATED ALWAYS AS (json_unquote(json_extract(`BussinessJson`,_utf8mb4'$.DynFormInfo.DynIsHelpers'))) VIRTUAL COMMENT '(Dyn)协助人',
  `v_DynVinNumber` varchar(50) GENERATED ALWAYS AS (json_unquote(json_extract(`BussinessJson`,_utf8mb4'$.DynFormInfo.DynVinNumber'))) VIRTUAL COMMENT '(Dyn)车架号',
  `v_OrderRelationId` varchar(36) GENERATED ALWAYS AS (json_unquote(json_extract(`BussinessJson`,_utf8mb4'$.OrderRelationId'))) VIRTUAL COMMENT '(百信)车务车电关联ID',
  `v_CustNoticeTag` varchar(50) GENERATED ALWAYS AS (json_unquote(json_extract(`BussinessJson`,_utf8mb4'$.CustNoticeTag'))) VIRTUAL COMMENT '(佰信)客户通知标识（0800 放款提交中）',
  `LastUpdateTimeStamp` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '最近更新时间',
  `v_chpWXAddProgress` varchar(50) GENERATED ALWAYS AS (json_unquote(json_extract(`BussinessJson`,_utf8mb4'$.chpWXAddProgress'))) VIRTUAL COMMENT '(CHP)车主微信添加进度',
  `v_chpCarUserName` varchar(50) GENERATED ALWAYS AS (json_unquote(json_extract(`BussinessJson`,_utf8mb4'$.chpCarUserName'))) VIRTUAL COMMENT '(CHP)车主姓名',
  `v_chpCarUserTel` varchar(50) GENERATED ALWAYS AS (json_unquote(json_extract(`BussinessJson`,_utf8mb4'$.chpCarUserTel'))) VIRTUAL COMMENT '(CHP)车主电话',
  `v_chpSurveyInstallType` varchar(50) GENERATED ALWAYS AS (json_unquote(json_extract(`BussinessJson`,_utf8mb4'$.chpSurveyInfo.InstallType'))) VIRTUAL COMMENT '(CHP)安装方式',
  `v_chpElectricityMetersType` varchar(50) GENERATED ALWAYS AS (json_unquote(json_extract(`BussinessJson`,_utf8mb4'$.chpSurveyInfo.ElectricityMetersType'))) VIRTUAL COMMENT '(CHP)电表类型',
  `v_IsExtraOrder` int(11) GENERATED ALWAYS AS (json_unquote(json_extract(`BussinessJson`,_utf8mb4'$.IsExtraOrder'))) VIRTUAL COMMENT '(VHS)创收工单标识',
  `v_chpFirstContactRole` smallint(6) GENERATED ALWAYS AS (if((json_unquote(json_extract(`BussinessJson`,_utf8mb4'$.chpFirstContact.Role')) = _utf8mb4''),0,json_unquote(json_extract(`BussinessJson`,_utf8mb4'$.chpFirstContact.Role')))) VIRTUAL COMMENT '(CHP)首联人角色(1-运营，2-服务人员)',
  `v_chpNextFollowTime` datetime GENERATED ALWAYS AS (if((json_unquote(json_extract(`BussinessJson`,_utf8mb4'$.chpNextFollowTime')) = _utf8mb4''),NULL,if((json_unquote(json_extract(`BussinessJson`,_utf8mb4'$.chpNextFollowTime')) = _utf8mb4'null'),NULL,json_unquote(json_extract(`BussinessJson`,_utf8mb4'$.chpNextFollowTime'))))) VIRTUAL COMMENT '(CHP)下次跟进时间',
  `v_chpCarVinNumber` varchar(100) GENERATED ALWAYS AS (json_unquote(json_extract(`BussinessJson`,_utf8mb4'$.chpCarVinNumber'))) VIRTUAL COMMENT '(CHP)车架号',
  `v_ChpLineActualUsage` int(11) GENERATED ALWAYS AS ((if((json_unquote(json_extract(json_extract(json_unquote(json_extract(`BussinessJson`,_utf8mb4'$.chpAccessories')),json_unquote(json_search(json_unquote(json_extract(`BussinessJson`,_utf8mb4'$.chpAccessories[*].AccessoriesType')),_utf8mb4'one',_utf8mb4'电缆硬线'))),_utf8mb4'$.ActualUsage')) in (_utf8mb4'null',_utf8mb4'')),0,json_unquote(json_extract(json_extract(json_unquote(json_extract(`BussinessJson`,_utf8mb4'$.chpAccessories')),json_unquote(json_search(json_unquote(json_extract(`BussinessJson`,_utf8mb4'$.chpAccessories[*].AccessoriesType')),_utf8mb4'one',_utf8mb4'电缆硬线'))),_utf8mb4'$.ActualUsage'))) + if((json_unquote(json_extract(json_extract(json_unquote(json_extract(`BussinessJson`,_utf8mb4'$.chpAccessories')),json_unquote(json_search(json_unquote(json_extract(`BussinessJson`,_utf8mb4'$.chpAccessories[*].AccessoriesType')),_utf8mb4'one',_utf8mb4'电缆软线'))),_utf8mb4'$.ActualUsage')) in (_utf8mb4'null',_utf8mb4'')),0,json_unquote(json_extract(json_extract(json_unquote(json_extract(`BussinessJson`,_utf8mb4'$.chpAccessories')),json_unquote(json_search(json_unquote(json_extract(`BussinessJson`,_utf8mb4'$.chpAccessories[*].AccessoriesType')),_utf8mb4'one',_utf8mb4'电缆软线'))),_utf8mb4'$.ActualUsage'))))) VIRTUAL COMMENT '(CHP)线缆实际用量（电缆硬线+电缆软线实际用量）',
  `v_chpFactoryBrand` varchar(200) GENERATED ALWAYS AS (json_unquote(json_extract(`BussinessJson`,_utf8mb4'$.chpFactoryBrand'))) VIRTUAL COMMENT '(CHP)主机厂品牌',
  `v_chpActualSolutionCode` varchar(200) GENERATED ALWAYS AS (json_unquote(json_extract(`BussinessJson`,_utf8mb4'$.chpActualSolutionCode'))) VIRTUAL COMMENT '(CHP)实际处理方案Code',
  `v_PostFillWorkOrder` tinyint(3) unsigned GENERATED ALWAYS AS (ifnull(json_unquote(json_extract(`BussinessJson`,_utf8mb4'$.PostFillWorkOrder')),0)) VIRTUAL COMMENT '(车电)后补工单(0-非后补，1-后补工单）',
  `v_chpOrderCompleteTime` datetime GENERATED ALWAYS AS (if((json_unquote(json_extract(`BussinessJson`,_utf8mb4'$.chpOrderCompleteTime')) = _utf8mb4'null'),NULL,json_unquote(json_extract(`BussinessJson`,_utf8mb4'$.chpOrderCompleteTime')))) VIRTUAL COMMENT '(CHP)工单完成时间',
  `v_afcAuditPassTime` datetime GENERATED ALWAYS AS (json_unquote(json_extract(`BussinessJson`,_utf8mb4'$.afcAuditPassTime'))) VIRTUAL COMMENT '(AFC)质检通过时间',
  `v_OrderColor` int(11) GENERATED ALWAYS AS (json_unquote(json_extract(`BussinessJson`,_utf8mb4'$.orderColor'))) VIRTUAL COMMENT '(AFC)工单卡片颜色',
  `v_CompleteAging` int(11) GENERATED ALWAYS AS (json_unquote(json_extract(`BussinessJson`,_utf8mb4'$.CompleteAging'))) VIRTUAL COMMENT '完单时效（0不合格 1合格）',
  `v_RescScreenshotAging` int(11) GENERATED ALWAYS AS (json_unquote(json_extract(`BussinessJson`,_utf8mb4'$.RescScreenshotAging'))) VIRTUAL COMMENT '改约截图时效（0不合格 1合格）',
  `v_RescScreenshotResult` int(11) GENERATED ALWAYS AS (json_unquote(json_extract(`BussinessJson`,_utf8mb4'$.RescScreenshotResult'))) VIRTUAL COMMENT '改约截图对比结果（0不合格 1合格）',
  `v_SecondVisitStatus` int(11) GENERATED ALWAYS AS (json_unquote(json_extract(`BussinessJson`,_utf8mb4'$.SecondVisitStatus'))) VIRTUAL COMMENT '(AFC)二访状态（0-待走访，1-走访中，2-走访完成，3-走访拒绝）',
  `v_MaxRescScreenshotTime` datetime GENERATED ALWAYS AS (json_unquote(json_extract(`BussinessJson`,_utf8mb4'$.MaxRescScreenshotTime'))) VIRTUAL COMMENT '最大改约有效时间（下单生效时间+工作时间6H（工作时间：8:30-18:00））',
  `v_SecondVisitTime` datetime GENERATED ALWAYS AS (json_unquote(json_extract(`BussinessJson`,_utf8mb4'$.SecondVisitTime'))) VIRTUAL COMMENT '(AFC)发起二访时间）',
  `v_OutCardDate` date GENERATED ALWAYS AS (json_unquote(json_extract(`BussinessJson`,_utf8mb4'$.OutCardDate'))) VIRTUAL COMMENT '(VHS)出证日期',
  `v_ToBeAuditTag` smallint(6) GENERATED ALWAYS AS (json_unquote(json_extract(`BussinessJson`,_utf8mb4'$.ToBeAuditTag'))) VIRTUAL COMMENT '(AFC)回款提报待审核标记',
  `v_tirePlateNumber` varchar(20) GENERATED ALWAYS AS (json_unquote(json_extract(`BussinessJson`,_utf8mb4'$.tirePlateNumber'))) VIRTUAL COMMENT '(胎联网)车牌号',
  `v_tireDeviceModel` varchar(200) GENERATED ALWAYS AS (json_unquote(json_extract(`BussinessJson`,_utf8mb4'$.tireDeviceModel'))) VIRTUAL COMMENT '(胎联网)设备型号',
  `v_tireNeedOuterTireRemoval` smallint(6) GENERATED ALWAYS AS (json_unquote(json_extract(`BussinessJson`,_utf8mb4'$.tireNeedOuterTireRemoval'))) VIRTUAL COMMENT '(胎联网)是否需要拆外侧轮胎',
  `v_tireRemovalCount` int(11) GENERATED ALWAYS AS (json_unquote(json_extract(`BussinessJson`,_utf8mb4'$.tireRemovalCount'))) VIRTUAL COMMENT '(胎联网)拆胎数量',
  `v_tireInstallationMethod` varchar(20) GENERATED ALWAYS AS (json_unquote(json_extract(`BussinessJson`,_utf8mb4'$.tireInstallationMethod'))) VIRTUAL COMMENT '(胎联网)安装方式',
  `v_tireReplacementReason` varchar(500) GENERATED ALWAYS AS (json_unquote(json_extract(`BussinessJson`,_utf8mb4'$.tireReplacementReason'))) VIRTUAL COMMENT '(胎联网)更换原因',
  `v_tireRemovalReason` varchar(500) GENERATED ALWAYS AS (json_unquote(json_extract(`BussinessJson`,_utf8mb4'$.tireRemovalReason'))) VIRTUAL COMMENT '(胎联网)拆回原因',
  `v_tireReplacementRemovalReason` varchar(500) GENERATED ALWAYS AS (json_unquote(json_extract(`BussinessJson`,_utf8mb4'$.tireReplacementRemovalReason'))) VIRTUAL COMMENT '(胎联网)更换拆回原因',
  `v_tirePosition` varchar(50) GENERATED ALWAYS AS (json_unquote(json_extract(`BussinessJson`,_utf8mb4'$.tirePosition'))) VIRTUAL COMMENT '(胎联网)轮胎轮位',
  `v_tireNumber` varchar(50) GENERATED ALWAYS AS (json_unquote(json_extract(`BussinessJson`,_utf8mb4'$.tireNumber'))) VIRTUAL COMMENT '(胎联网)胎号',
  `v_tirePositionChangeReason` varchar(50) GENERATED ALWAYS AS (json_unquote(json_extract(`BussinessJson`,_utf8mb4'$.tirePositionChangeReason'))) VIRTUAL COMMENT '(胎联网)换位原因',
  `v_tirePositionChangeSuggestion` varchar(50) GENERATED ALWAYS AS (json_unquote(json_extract(`BussinessJson`,_utf8mb4'$.tirePositionChangeSuggestion'))) VIRTUAL COMMENT '(胎联网)换位建议',
  `v_tireInflationPosition` varchar(50) GENERATED ALWAYS AS (json_unquote(json_extract(`BussinessJson`,_utf8mb4'$.tireInflationPosition'))) VIRTUAL COMMENT '(胎联网)充气轮胎轮位',
  `v_tirePressure` varchar(50) GENERATED ALWAYS AS (json_unquote(json_extract(`BussinessJson`,_utf8mb4'$.tirePressure'))) VIRTUAL COMMENT '(胎联网)胎压',
  `v_tireRemovalInstallationPosition` varchar(50) GENERATED ALWAYS AS (json_unquote(json_extract(`BussinessJson`,_utf8mb4'$.tireRemovalInstallationPosition'))) VIRTUAL COMMENT '(胎联网)拆装轮胎轮位',
  `v_tireInspectedVehicleCount` varchar(50) GENERATED ALWAYS AS (json_unquote(json_extract(`BussinessJson`,_utf8mb4'$.tireInspectedVehicleCount'))) VIRTUAL COMMENT '(胎联网)巡检车辆数量',
  `v_tireIsSupplementaryOrder` varchar(10) GENERATED ALWAYS AS (json_unquote(json_extract(`BussinessJson`,_utf8mb4'$.tireIsSupplementaryOrder'))) VIRTUAL COMMENT '(胎联网)是否后补工单(0否 1是)',
  `v_tireRepairTypeId` varchar(20) GENERATED ALWAYS AS (json_unquote(json_extract(`BussinessJson`,_utf8mb4'$.tireRepairTypeId'))) VIRTUAL COMMENT '(胎联网)修复方式Id(basic_datadictionary.Id)',
  `v_tireRepairTypeName` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci GENERATED ALWAYS AS (json_unquote(json_extract(`BussinessJson`,_utf8mb4'$.tireRepairTypeName'))) VIRTUAL COMMENT '(胎联网)其他修复方式',
  `v_tireIssueSummary` varchar(500) GENERATED ALWAYS AS (json_unquote(json_extract(`BussinessJson`,_utf8mb4'$.tireIssueSummary'))) VIRTUAL COMMENT '(胎联网)轮胎问题汇总',
  `v_chpCarModel` varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci GENERATED ALWAYS AS (json_unquote(json_extract(`BussinessJson`,_utf8mb4'$.chpCarModel'))) VIRTUAL COMMENT '(CHP)车型',
  `v_CustomerAuditStatus` int(11) GENERATED ALWAYS AS (json_unquote(json_extract(`BussinessJson`,_utf8mb4'$.CustomerAuditStatus'))) VIRTUAL COMMENT '客户审核状态',
  `v_need_reinstall` varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci GENERATED ALWAYS AS (json_unquote(json_extract(json_extract(`BussinessJson`,_utf8mb4'$.ExtraFields'),_utf8mb4'$.need_reinstall'))) VIRTUAL COMMENT '(车电)是否更换设备--民生',
  `v_SelfOperatedInstallId` varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci GENERATED ALWAYS AS (json_unquote(json_extract(json_extract(`BussinessJson`,_utf8mb4'$.SelfOperatedInstallId'),_utf8mb4'$.SelfOperatedInstallId'))) VIRTUAL COMMENT '(车电)自营安装工单 ID',
  PRIMARY KEY (`Id`,`DynamicId`),
  KEY `NON-WorkOrderId` (`WorkOrderId`),
  KEY `NON-DynamicId` (`DynamicId`) USING BTREE,
  KEY `NON-LastUpdateTimeStamp` (`LastUpdateTimeStamp`),
  KEY `NON-AfcCompleteType` (`v_AfcCompleteType`),
  KEY `NON-AppointTime` (`appointTime`),
  KEY `NON-AppraisalStatus` (`AppraisalStatus`),
  KEY `NON-FollowFrequency` (`v_FollowFrequency`),
  KEY `NON-FollowFrequencyType` (`v_FollowFrequencyType`),
  KEY `NON-IfEtcRecord` (`v_IfEtcRecord`),
  KEY `NON-IfRemove` (`v_IfRemove`),
  KEY `NON-IsRelateEtc` (`v_IsRelateEtc`),
  KEY `NON-NegotiatorTime` (`v_LastNegotiatorTime`),
  KEY `NON-ReportDeadline` (`v_ReportDeadline`),
  KEY `NON-ReturnedTypeCode` (`v_ReturnedTypeCode`),
  KEY `NON-UnFollowDays` (`v_UnFollowDays`),
  KEY `NON_RescuerName` (`v_RescuerName`),
  KEY `NON_RescuerPlateNumber` (`v_RescuerPlateNumber`),
  KEY `NON_RescuerTel` (`v_RescuerTel`),
  KEY `NON-RelateWorkOrderId` (`v_RelateWorkOrderId`),
  KEY `NON-DynIsHelpers` (`v_DynIsHelpers`),
  KEY `NON-DynVinNumber` (`v_DynVinNumber`),
  KEY `NON-v_chpWXAddProgress` (`v_chpWXAddProgress`) USING BTREE,
  KEY `NON-v_chpCarUserName` (`v_chpCarUserName`) USING BTREE,
  KEY `NON-v_chpCarUserTel` (`v_chpCarUserTel`) USING BTREE,
  KEY `NON-v_chpSurveyInstallType` (`v_chpSurveyInstallType`) USING BTREE,
  KEY `NON-v_chpElectricityMetersType` (`v_chpElectricityMetersType`) USING BTREE,
  KEY `NON-v_IsExtraOrder` (`v_IsExtraOrder`) USING BTREE,
  KEY `NON-v_OrderRelationId` (`v_OrderRelationId`),
  KEY `NON-v_chpFirstContactRole` (`v_chpFirstContactRole`) USING BTREE,
  KEY `NON-v_chpNextFollowTime` (`v_chpNextFollowTime`) USING BTREE,
  KEY `NON-v_chpCarVinNumber` (`v_chpCarVinNumber`) USING BTREE,
  KEY `NON-v_chpFactoryBrand` (`v_chpFactoryBrand`),
  KEY `NON-v_chpActualSolutionCode` (`v_chpActualSolutionCode`),
  KEY `NON-v_PostFillWorkOrder` (`v_PostFillWorkOrder`),
  KEY `NON-chpOrderCompleteTime` (`v_chpOrderCompleteTime`),
  KEY `v_afcAuditPassTime` (`v_afcAuditPassTime`),
  KEY `v_OrderColor` (`v_OrderColor`),
  KEY `NON-v_CompleteAging` (`v_CompleteAging`),
  KEY `NON-v_RescScreenshotAging` (`v_RescScreenshotAging`),
  KEY `NON-v_RescScreenshotResult` (`v_RescScreenshotResult`),
  KEY `NON-v_SecondVisitStatus` (`v_SecondVisitStatus`),
  KEY `NON-v_MaxRescScreenshotTime` (`v_MaxRescScreenshotTime`),
  KEY `NON-v_SecondVisitTime` (`v_SecondVisitTime`),
  KEY `NON-v_OutCardDate` (`v_OutCardDate`),
  KEY `NON-v_CustomerAuditStatus` (`v_CustomerAuditStatus`) USING BTREE,
  KEY `NON-v_need_reinstall` (`v_need_reinstall`) USING BTREE,
  KEY `NON-v_SelfOperatedInstallId` (`v_SelfOperatedInstallId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 ROW_FORMAT=DYNAMIC COMMENT='业务域_工单业务信息JOSN冗余表'
;

INSERT INTO serviceordercenterhistest.tb_workbussinessjsoninfo(Id,WorkOrderId,BussinessJson,InsertTime,Deleted)
SELECT Id,WorkOrderId,BussinessJson,InsertTime,Deleted
FROM serviceordercenter.tb_workbussinessjsoninfo;